import fs from 'node:fs';
const src = fs.readFileSync('src/content/extra-articles.js', 'utf8');
const re = /["']?slug["']?\s*:\s*["']([^"']+)["']/g;
const m = [...src.matchAll(re)];
console.log('matches:', m.length, m.slice(0, 3).map((x) => x[1]));
console.log('--- test line by line ---');
const line = "    slug: 'come-scegliere-uno-psicologo',";
console.log(line.match(re));
const re2 = /["']?slug["']?\s*:\s*["']([^"']+)["']/g;
re2.lastIndex = 0;
console.log([...line.matchAll(re2)].map((x) => x[1]));
