// Capoluoghi di provincia italiani per le pagine "psicologo online [città]".
// Il servizio è online da tutta Italia: le pagine catturano la ricerca locale.
// Struttura: { nome, slug, provincia, regione }

export const citta = [
  { nome: 'Agrigento', slug: 'agrigento', provincia: 'Agrigento', regione: 'Sicilia' },
  { nome: 'Alessandria', slug: 'alessandria', provincia: 'Alessandria', regione: 'Piemonte' },
  { nome: 'Ancona', slug: 'ancona', provincia: 'Ancona', regione: 'Marche' },
  { nome: 'Aosta', slug: 'aosta', provincia: 'Aosta', regione: 'Valle d\'Aosta' },
  { nome: 'Arezzo', slug: 'arezzo', provincia: 'Arezzo', regione: 'Toscana' },
  { nome: 'Ascoli Piceno', slug: 'ascoli-piceno', provincia: 'Ascoli Piceno', regione: 'Marche' },
  { nome: 'Asti', slug: 'asti', provincia: 'Asti', regione: 'Piemonte' },
  { nome: 'Avellino', slug: 'avellino', provincia: 'Avellino', regione: 'Campania' },
  { nome: 'Bari', slug: 'bari', provincia: 'Bari', regione: 'Puglia' },
  { nome: 'Barletta', slug: 'barletta', provincia: 'Barletta-Andria-Trani', regione: 'Puglia' },
  { nome: 'Belluno', slug: 'belluno', provincia: 'Belluno', regione: 'Veneto' },
  { nome: 'Benevento', slug: 'benevento', provincia: 'Benevento', regione: 'Campania' },
  { nome: 'Bergamo', slug: 'bergamo', provincia: 'Bergamo', regione: 'Lombardia' },
  { nome: 'Biella', slug: 'biella', provincia: 'Biella', regione: 'Piemonte' },
  { nome: 'Bologna', slug: 'bologna', provincia: 'Bologna', regione: 'Emilia-Romagna' },
  { nome: 'Bolzano', slug: 'bolzano', provincia: 'Bolzano', regione: 'Trentino-Alto Adige' },
  { nome: 'Brescia', slug: 'brescia', provincia: 'Brescia', regione: 'Lombardia' },
  { nome: 'Brindisi', slug: 'brindisi', provincia: 'Brindisi', regione: 'Puglia' },
  { nome: 'Cagliari', slug: 'cagliari', provincia: 'Cagliari', regione: 'Sardegna' },
  { nome: 'Caltanissetta', slug: 'caltanissetta', provincia: 'Caltanissetta', regione: 'Sicilia' },
  { nome: 'Campobasso', slug: 'campobasso', provincia: 'Campobasso', regione: 'Molise' },
  { nome: 'Carbonia', slug: 'carbonia', provincia: 'Sud Sardegna', regione: 'Sardegna' },
  { nome: 'Caserta', slug: 'caserta', provincia: 'Caserta', regione: 'Campania' },
  { nome: 'Catania', slug: 'catania', provincia: 'Catania', regione: 'Sicilia' },
  { nome: 'Catanzaro', slug: 'catanzaro', provincia: 'Catanzaro', regione: 'Calabria' },
  { nome: 'Chieti', slug: 'chieti', provincia: 'Chieti', regione: 'Abruzzo' },
  { nome: 'Como', slug: 'como', provincia: 'Como', regione: 'Lombardia' },
  { nome: 'Cosenza', slug: 'cosenza', provincia: 'Cosenza', regione: 'Calabria' },
  { nome: 'Cremona', slug: 'cremona', provincia: 'Cremona', regione: 'Lombardia' },
  { nome: 'Crotone', slug: 'crotone', provincia: 'Crotone', regione: 'Calabria' },
  { nome: 'Cuneo', slug: 'cuneo', provincia: 'Cuneo', regione: 'Piemonte' },
  { nome: 'Enna', slug: 'enna', provincia: 'Enna', regione: 'Sicilia' },
  { nome: 'Fermo', slug: 'fermo', provincia: 'Fermo', regione: 'Marche' },
  { nome: 'Ferrara', slug: 'ferrara', provincia: 'Ferrara', regione: 'Emilia-Romagna' },
  { nome: 'Firenze', slug: 'firenze', provincia: 'Firenze', regione: 'Toscana' },
  { nome: 'Foggia', slug: 'foggia', provincia: 'Foggia', regione: 'Puglia' },
  { nome: 'Forlì', slug: 'forli', provincia: 'Forlì-Cesena', regione: 'Emilia-Romagna' },
  { nome: 'Frosinone', slug: 'frosinone', provincia: 'Frosinone', regione: 'Lazio' },
  { nome: 'Genova', slug: 'genova', provincia: 'Genova', regione: 'Liguria' },
  { nome: 'Gorizia', slug: 'gorizia', provincia: 'Gorizia', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Grosseto', slug: 'grosseto', provincia: 'Grosseto', regione: 'Toscana' },
  { nome: 'Imperia', slug: 'imperia', provincia: 'Imperia', regione: 'Liguria' },
  { nome: 'Isernia', slug: 'isernia', provincia: 'Isernia', regione: 'Molise' },
  { nome: 'L\'Aquila', slug: 'l-aquila', provincia: 'L\'Aquila', regione: 'Abruzzo' },
  { nome: 'La Spezia', slug: 'la-spezia', provincia: 'La Spezia', regione: 'Liguria' },
  { nome: 'Latina', slug: 'latina', provincia: 'Latina', regione: 'Lazio' },
  { nome: 'Lecce', slug: 'lecce', provincia: 'Lecce', regione: 'Puglia' },
  { nome: 'Lecco', slug: 'lecco', provincia: 'Lecco', regione: 'Lombardia' },
  { nome: 'Livorno', slug: 'livorno', provincia: 'Livorno', regione: 'Toscana' },
  { nome: 'Lodi', slug: 'lodi', provincia: 'Lodi', regione: 'Lombardia' },
  { nome: 'Lucca', slug: 'lucca', provincia: 'Lucca', regione: 'Toscana' },
  { nome: 'Macerata', slug: 'macerata', provincia: 'Macerata', regione: 'Marche' },
  { nome: 'Mantova', slug: 'mantova', provincia: 'Mantova', regione: 'Lombardia' },
  { nome: 'Massa', slug: 'massa', provincia: 'Massa-Carrara', regione: 'Toscana' },
  { nome: 'Matera', slug: 'matera', provincia: 'Matera', regione: 'Basilicata' },
  { nome: 'Messina', slug: 'messina', provincia: 'Messina', regione: 'Sicilia' },
  { nome: 'Milano', slug: 'milano', provincia: 'Milano', regione: 'Lombardia' },
  { nome: 'Modena', slug: 'modena', provincia: 'Modena', regione: 'Emilia-Romagna' },
  { nome: 'Monza', slug: 'monza', provincia: 'Monza e Brianza', regione: 'Lombardia' },
  { nome: 'Napoli', slug: 'napoli', provincia: 'Napoli', regione: 'Campania' },
  { nome: 'Novara', slug: 'novara', provincia: 'Novara', regione: 'Piemonte' },
  { nome: 'Nuoro', slug: 'nuoro', provincia: 'Nuoro', regione: 'Sardegna' },
  { nome: 'Oristano', slug: 'oristano', provincia: 'Oristano', regione: 'Sardegna' },
  { nome: 'Padova', slug: 'padova', provincia: 'Padova', regione: 'Veneto' },
  { nome: 'Palermo', slug: 'palermo', provincia: 'Palermo', regione: 'Sicilia' },
  { nome: 'Parma', slug: 'parma', provincia: 'Parma', regione: 'Emilia-Romagna' },
  { nome: 'Pavia', slug: 'pavia', provincia: 'Pavia', regione: 'Lombardia' },
  { nome: 'Perugia', slug: 'perugia', provincia: 'Perugia', regione: 'Umbria' },
  { nome: 'Pesaro', slug: 'pesaro', provincia: 'Pesaro-Urbino', regione: 'Marche' },
  { nome: 'Pescara', slug: 'pescara', provincia: 'Pescara', regione: 'Abruzzo' },
  { nome: 'Piacenza', slug: 'piacenza', provincia: 'Piacenza', regione: 'Emilia-Romagna' },
  { nome: 'Pisa', slug: 'pisa', provincia: 'Pisa', regione: 'Toscana' },
  { nome: 'Pistoia', slug: 'pistoia', provincia: 'Pistoia', regione: 'Toscana' },
  { nome: 'Pordenone', slug: 'pordenone', provincia: 'Pordenone', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Potenza', slug: 'potenza', provincia: 'Potenza', regione: 'Basilicata' },
  { nome: 'Prato', slug: 'prato', provincia: 'Prato', regione: 'Toscana' },
  { nome: 'Ragusa', slug: 'ragusa', provincia: 'Ragusa', regione: 'Sicilia' },
  { nome: 'Ravenna', slug: 'ravenna', provincia: 'Ravenna', regione: 'Emilia-Romagna' },
  { nome: 'Reggio Calabria', slug: 'reggio-calabria', provincia: 'Reggio Calabria', regione: 'Calabria' },
  { nome: 'Reggio Emilia', slug: 'reggio-emilia', provincia: 'Reggio Emilia', regione: 'Emilia-Romagna' },
  { nome: 'Rieti', slug: 'rieti', provincia: 'Rieti', regione: 'Lazio' },
  { nome: 'Rimini', slug: 'rimini', provincia: 'Rimini', regione: 'Emilia-Romagna' },
  { nome: 'Roma', slug: 'roma', provincia: 'Roma', regione: 'Lazio' },
  { nome: 'Rovigo', slug: 'rovigo', provincia: 'Rovigo', regione: 'Veneto' },
  { nome: 'Salerno', slug: 'salerno', provincia: 'Salerno', regione: 'Campania' },
  { nome: 'Sassari', slug: 'sassari', provincia: 'Sassari', regione: 'Sardegna' },
  { nome: 'Savona', slug: 'savona', provincia: 'Savona', regione: 'Liguria' },
  { nome: 'Siena', slug: 'siena', provincia: 'Siena', regione: 'Toscana' },
  { nome: 'Siracusa', slug: 'siracusa', provincia: 'Siracusa', regione: 'Sicilia' },
  { nome: 'Sondrio', slug: 'sondrio', provincia: 'Sondrio', regione: 'Lombardia' },
  { nome: 'Taranto', slug: 'taranto', provincia: 'Taranto', regione: 'Puglia' },
  { nome: 'Teramo', slug: 'teramo', provincia: 'Teramo', regione: 'Abruzzo' },
  { nome: 'Terni', slug: 'terni', provincia: 'Terni', regione: 'Umbria' },
  { nome: 'Torino', slug: 'torino', provincia: 'Torino', regione: 'Piemonte' },
  { nome: 'Trani', slug: 'trani', provincia: 'Barletta-Andria-Trani', regione: 'Puglia' },
  { nome: 'Trapani', slug: 'trapani', provincia: 'Trapani', regione: 'Sicilia' },
  { nome: 'Trento', slug: 'trento', provincia: 'Trento', regione: 'Trentino-Alto Adige' },
  { nome: 'Treviso', slug: 'treviso', provincia: 'Treviso', regione: 'Veneto' },
  { nome: 'Trieste', slug: 'trieste', provincia: 'Trieste', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Udine', slug: 'udine', provincia: 'Udine', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Urbino', slug: 'urbino', provincia: 'Pesaro-Urbino', regione: 'Marche' },
  { nome: 'Varese', slug: 'varese', provincia: 'Varese', regione: 'Lombardia' },
  { nome: 'Venezia', slug: 'venezia', provincia: 'Venezia', regione: 'Veneto' },
  { nome: 'Verbania', slug: 'verbania', provincia: 'Verbano-Cusio-Ossola', regione: 'Piemonte' },
  { nome: 'Vercelli', slug: 'vercelli', provincia: 'Vercelli', regione: 'Piemonte' },
  { nome: 'Verona', slug: 'verona', provincia: 'Verona', regione: 'Veneto' },
  { nome: 'Vibo Valentia', slug: 'vibo-valentia', provincia: 'Vibo Valentia', regione: 'Calabria' },
  { nome: 'Vicenza', slug: 'vicenza', provincia: 'Vicenza', regione: 'Veneto' },
  { nome: 'Viterbo', slug: 'viterbo', provincia: 'Viterbo', regione: 'Lazio' },
];
