// citta-en.js — traduzione EN delle città top
export const cittaEn = [
  {
    nome: 'Milano',
    slug: 'milano',
    provincia: 'Milano',
    regione: 'Lombardia',
    intro: 'In Milan, fast-paced work rhythms and daily pressure often leave little room for well-being. Online therapy eliminates the need to commute, allowing you to book sessions whenever you\'re free, even late in the evening.',
    desc: 'Online psychologist in Milano: video sessions from €45, first session free. Professional support for work stress and anxiety from the comfort of your home.',
  },
  {
    nome: 'Roma',
    slug: 'roma',
    provincia: 'Roma',
    regione: 'Lazio',
    intro: 'In Rome, traffic stress, long commutes, and the pressure of studies can be overwhelming. With Adatto x Te, you can access therapy via secure video calls without the hassle of queues or waiting times across the capital.',
    desc: 'Online psychologist in Roma: video sessions from €45, first session free. Qualified therapists for anxiety, couples therapy, and exam preparation.',
  },
  {
    nome: 'Napoli',
    slug: 'napoli',
    provincia: 'Napoli',
    regione: 'Campania',
    intro: 'In Naples and its surrounding province, online therapy allows you to start your journey without being tied to clinic hours or travel times. Connect whenever and wherever it suits you best.',
    desc: 'Online psychologist in Napoli: secure video sessions from €45, first meeting free. Support for anxiety, depression, and relationships with expert therapists.',
  },
  {
    nome: 'Torino',
    slug: 'torino',
    provincia: 'Torino',
    regione: 'Piemonte',
    intro: 'In Turin, balancing work and family life can be challenging. Adatto x Te\'s online sessions fit into your busy schedule, saving you from commuting across the city to see a professional.',
    desc: 'Online psychologist in Torino: video sessions from €45, first session free. Professional support for anxiety and relationship issues available online.',
  },
  {
    nome: 'Bari',
    slug: 'bari',
    provincia: 'Bari',
    regione: 'Puglia',
    intro: 'In Bari and throughout Puglia, online therapy makes psychological support accessible even for those with difficult schedules or living far from major centers. Simply book, pay, and connect.',
    desc: 'Online psychologist in Bari: video sessions from €45, first meeting free. Support for anxiety, sports psychology, and couples from qualified professionals.',
  },
  {
    nome: 'Bologna',
    slug: 'bologna',
    provincia: 'Bologna',
    regione: 'Emilia-Romagna',
    intro: 'In Bologna, a major university city, exam anxiety and study pressure are common reasons to start therapy. Find specialized support without even leaving your desk.',
    desc: 'Online psychologist in Bologna: video sessions from €45, first session free. Ideal for students and professionals looking for flexible therapy options.',
  },
  {
    nome: 'Firenze',
    slug: 'firenze',
    provincia: 'Firenze',
    regione: 'Toscana',
    intro: 'In Florence, taking care of your mental health should be simple despite the city\'s busy pace. Our online sessions offer expert support without the need for travel or waiting rooms.',
    desc: 'Online psychologist in Firenze: video sessions from €45, first session free. Qualified support for anxiety, couples, and personal growth in video call.',
  },
  {
    nome: 'Verona',
    slug: 'verona',
    provincia: 'Verona',
    regione: 'Veneto',
    intro: 'In Verona and its province, online therapy adapts to your lifestyle, whether you\'re balancing work, family, or the demands of a tourist city. Connect for 50 minutes from wherever you prefer.',
    desc: 'Online psychologist in Verona: video sessions from €45, first meeting free. Professional support for anxiety, work stress, and relationships online.',
  },
  {
    nome: 'Palermo',
    slug: 'palermo',
    provincia: 'Palermo',
    regione: 'Sicilia',
    intro: 'In Palermo, as in the rest of Sicily, online psychology removes geographical barriers. A secure connection and a device are all you need to start a journey with qualified professionals.',
    desc: 'Online psychologist in Palermo: video sessions from €45, first session free. Support for anxiety, couples, and sports psychology available via video call.',
  },
  {
    nome: 'Genova',
    slug: 'genova',
    provincia: 'Genova',
    regione: 'Liguria',
    intro: 'In Genoa, finding the right time for therapy is easier with online sessions that bypass the city\'s unique geography and commuting challenges. Book and connect at your convenience.',
    desc: 'Online psychologist in Genova: video sessions from €45, first meeting free. Convenient support for anxiety and stress without commuting across the city.',
  },
  {
    nome: 'Padova',
    slug: 'padova',
    provincia: 'Padova',
    regione: 'Veneto',
    intro: 'In the university city of Padua, exam stress and academic pressure are frequent challenges. Get specialized video support without leaving your study space.',
    desc: 'Online psychologist in Padova: video sessions from €45, first meeting free. Flexible support for students, workers, and families via secure video call.',
  },
  {
    nome: 'Catania',
    slug: 'catania',
    provincia: 'Catania',
    regione: 'Sicilia',
    intro: 'In Catania and the Etna province, starting an online psychological path allows you to receive support from home, regardless of studio hours or travel constraints.',
    desc: 'Online psychologist in Catania: video sessions from €45, first session free. Support for anxiety, depression, and relationships with qualified therapists.',
  },
  {
    nome: 'Bergamo',
    slug: 'bergamo',
    provincia: 'Bergamo',
    regione: 'Lombardia',
    intro: 'In Bergamo, online therapy makes it easier to find time for yourself amidst commuting and busy work schedules. Book and connect from wherever you are.',
    desc: 'Online psychologist in Bergamo: video sessions from €45, first meeting free. Support for anxiety, work-related stress, and relationships available online.',
  },
  {
    nome: 'Brescia',
    slug: 'brescia',
    provincia: 'Brescia',
    regione: 'Lombardia',
    intro: 'In Brescia, online therapy eliminates obstacles by fitting 50-minute video sessions into your life, whether you\'re managing work, family, or travel.',
    desc: 'Online psychologist in Brescia: video sessions from €45, first session free. Professional support for work stress and anxiety from the comfort of home.',
  },
  {
    nome: 'Cagliari',
    slug: 'cagliari',
    provincia: 'Cagliari',
    regione: 'Sardegna',
    intro: 'In Cagliari and across Sardinia, where distances can be a barrier, online therapy makes support accessible to everyone without the need for travel or waiting times.',
    desc: 'Online psychologist in Cagliari: video sessions from €45, first meeting free. Accessible therapy that overcomes geographical distances via video call.',
  },
  {
    nome: 'Venezia',
    slug: 'venezia',
    provincia: 'Venezia',
    regione: 'Veneto',
    intro: 'In Venice and its mainland, commuting can be long and costly. Our 50-minute video sessions bring the therapist to you, at home or in the office, saving you the boat trip.',
    desc: 'Online psychologist in Venezia: video sessions from €45, first meeting free. No boat trip required: receive professional support from home via video.',
  },
  {
    nome: 'Parma',
    slug: 'parma',
    provincia: 'Parma',
    regione: 'Emilia-Romagna',
    intro: 'In Parma, fitting mental health care into a busy family and work life is simpler with online therapy. Book your session when you\'re free and connect from home or work.',
    desc: 'Online psychologist in Parma: video sessions from €45, first session free. Qualified support for anxiety, couples, and personal growth via video call.',
  },
  {
    nome: 'Modena',
    slug: 'modena',
    provincia: 'Modena',
    regione: 'Emilia-Romagna',
    intro: 'In Modena, a city of industry and work, daily pressure often leaves little room for well-being. Take care of yourself without commuting, even during your lunch break.',
    desc: 'Online psychologist in Modena: video sessions from €45, first meeting free. Support for anxiety, work stress, and relationships with expert therapists.',
  },
  {
    nome: 'Reggio Emilia',
    slug: 'reggio-emilia',
    provincia: 'Reggio Emilia',
    regione: 'Emilia-Romagna',
    intro: 'In Reggio Emilia, online therapy offers a convenient and flexible solution for busy professionals and those who travel frequently for work.',
    desc: 'Online psychologist in Reggio Emilia: video sessions from €45, first session free. Flexible and professional support for anxiety and relationship issues.',
  },
  {
    nome: 'Perugia',
    slug: 'perugia',
    provincia: 'Perugia',
    regione: 'Umbria',
    intro: 'In Perugia, with its vibrant student community, online therapy provides accessible support in multiple languages, tailored to your academic and personal needs.',
    desc: 'Online psychologist in Perugia: video sessions from €45, first meeting free. Support for students and professionals available in multiple languages.',
  },
  {
    nome: 'Pescara',
    slug: 'pescara',
    provincia: 'Pescara',
    regione: 'Abruzzo',
    intro: 'In Pescara and throughout Abruzzo, online therapy bridges the distances of the region, offering 50-minute video sessions from the comfort of your home or office.',
    desc: 'Online psychologist in Pescara: video sessions from €45, first session free. Support for anxiety, couples, and personal growth via secure video call.',
  },
  {
    nome: 'Rimini',
    slug: 'rimini',
    provincia: 'Rimini',
    regione: 'Emilia-Romagna',
    intro: 'In Rimini, where seasonal work can make schedules unpredictable, online therapy ensures you can maintain consistent support all year round, regardless of your location.',
    desc: 'Online psychologist in Rimini: video sessions from €45, first meeting free. Consistent support for anxiety and stress, adapting to your seasonal schedule.',
  },
  {
    nome: 'Lecce',
    slug: 'lecce',
    provincia: 'Lecce',
    regione: 'Puglia',
    intro: 'In Lecce and the Salento area, online therapy brings psychological support directly to your home, requiring only a device and a connection to overcome local distances.',
    desc: 'Online psychologist in Lecce: video sessions from €45, first session free. Accessible therapy for anxiety and relationships throughout the Salento region.',
  },
  {
    nome: 'Trento',
    slug: 'trento',
    provincia: 'Trento',
    regione: 'Trentino-Alto Adige',
    intro: 'In Trento and its surrounding valleys, where travel between towns can be difficult, online therapy brings support to you wherever you are, requiring only a connection.',
    desc: 'Online psychologist in Trento: video sessions from €45, first meeting free. Professional support for anxiety and work stress, overcoming mountain distances.',
  },
  {
    nome: 'Trieste',
    slug: 'trieste',
    provincia: 'Trieste',
    regione: 'Friuli-Venezia Giulia',
    intro: 'In the international city of Trieste, online therapy offers flexibility and privacy, with sessions available in multiple languages to suit a diverse community.',
    desc: 'Online psychologist in Trieste: video sessions from €45, first session free. Qualified therapists offering support in multiple languages via video call.',
  },
  {
    nome: 'Ancona',
    slug: 'ancona',
    provincia: 'Ancona',
    regione: 'Marche',
    intro: 'As the capital of Marche, Ancona lives between the port and the hills. Our online support reaches you via video call, perfect for those working or studying away from home.',
    desc: 'Online psychologist in Ancona: video sessions from €45, first meeting free. Support for anxiety, couples, and personal growth available via video call.',
  },
  {
    nome: 'Pisa',
    slug: 'pisa',
    provincia: 'Pisa',
    regione: 'Toscana',
    intro: 'In Pisa, both students and workers benefit from the flexibility of online therapy, ensuring continuous support that fits around academic and professional commitments.',
    desc: 'Online psychologist in Pisa: video sessions from €45, first session free. Flexible support for students and families from qualified professionals.',
  },
  {
    nome: 'Lucca',
    slug: 'lucca',
    provincia: 'Lucca',
    regione: 'Toscana',
    intro: 'In Lucca, between its historic walls and the countryside, online psychological support respects your schedule and eliminates the need for travel.',
    desc: 'Online psychologist in Lucca: video sessions from €45, first meeting free. Discreet and professional support for anxiety and personal growth online.',
  },
  {
    nome: 'Como',
    slug: 'como',
    provincia: 'Como',
    regione: 'Lombardia',
    intro: 'In Como and along its lake, online therapy removes the need for commuting, providing total schedule flexibility for those living on the water or working in nearby cities.',
    desc: 'Online psychologist in Como: video sessions from €45, first session free. Professional support for work stress and anxiety without the commute.',
  },
  {
    nome: 'Salerno',
    slug: 'salerno',
    provincia: 'Salerno',
    regione: 'Campania',
    intro: 'In Salerno and its province, online therapy allows you to receive psychological support without compromise, easily fitting into your daily routine and commute.',
    desc: 'Online psychologist in Salerno: video sessions from €45, first meeting free. Flexible support for anxiety, couples, and personal growth via video call.',
  },
];
