// Capoluoghi di provincia italiani per le pagine "psicologo online [città]".
// Il servizio è online da tutta Italia: le pagine catturano la ricerca locale.
// Struttura: { nome, slug, provincia, regione }

export const citta = [
  { nome: 'Agrigento', slug: 'agrigento', provincia: 'Agrigento', regione: 'Sicilia' },
  { nome: 'Alessandria', slug: 'alessandria', provincia: 'Alessandria', regione: 'Piemonte' },
  { nome: 'Ancona', slug: 'ancona', provincia: 'Ancona', regione: 'Marche' },
  { nome: 'Aosta', slug: 'aosta', provincia: 'Aosta', regione: 'Valle d\'Aosta' },
  { nome: 'Arezzo', slug: 'arezzo', provincia: 'Arezzo', regione: 'Toscana' },
  { nome: 'Ascoli Piceno', slug: 'ascoli-piceno', provincia: 'Ascoli Piceno', regione: 'Marche' },
  { nome: 'Asti', slug: 'asti', provincia: 'Asti', regione: 'Piemonte' },
  { nome: 'Avellino', slug: 'avellino', provincia: 'Avellino', regione: 'Campania' },
  {
    nome: 'Bari',
    slug: 'bari',
    provincia: 'Bari',
    regione: 'Puglia',
    intro: 'A Bari e in tutta la Puglia, la terapia online rende il supporto psicologico accessibile anche a chi ha orari difficili o vive lontano dai centri: prenoti, paghi e ti colleghi in videochiamata.',
    faqExtra: [
      ['Quali specialisti sono disponibili per chi vive a Bari?', 'Trovi psicologi per ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: confronta i profili e scegli.'],
      ['Posso scrivere al terapeuta tra una seduta e l\'altra?', 'Sì, su Adatto x Te i messaggi con il terapeuta sono illimitati: puoi restare in contatto tra una seduta e l\'altra.'],
    ],
  },
  { nome: 'Barletta', slug: 'barletta', provincia: 'Barletta-Andria-Trani', regione: 'Puglia' },
  { nome: 'Belluno', slug: 'belluno', provincia: 'Belluno', regione: 'Veneto' },
  { nome: 'Benevento', slug: 'benevento', provincia: 'Benevento', regione: 'Campania' },
  { nome: 'Bergamo', slug: 'bergamo', provincia: 'Bergamo', regione: 'Lombardia' },
  { nome: 'Biella', slug: 'biella', provincia: 'Biella', regione: 'Piemonte' },
  {
    nome: 'Bologna',
    slug: 'bologna',
    provincia: 'Bologna',
    regione: 'Emilia-Romagna',
    intro: 'A Bologna, città universitaria per eccellenza, ansia da esame e pressione degli studi sono tra i motivi più comuni per iniziare un percorso: con Adatto x Te trovi supporto specializzato senza spostarti dalla scrivania.',
    faqExtra: [
      ['Sono uno studente universitario a Bologna: posso prenotare sedute tra un esame e l\'altro?', 'Certo: prenoti online l\'orario che preferisci, anche con pochi giorni di anticipo, e annulli o sposti la seduta senza complicazioni.'],
      ['Esistono sconti per i pacchetti?', 'Sì: il pacchetto di 3 sedute ha uno sconto del 15%, così il percorso continuativo costa meno della singola seduta.'],
    ],
  },
  { nome: 'Bolzano', slug: 'bolzano', provincia: 'Bolzano', regione: 'Trentino-Alto Adige' },
  { nome: 'Brescia', slug: 'brescia', provincia: 'Brescia', regione: 'Lombardia' },
  { nome: 'Brindisi', slug: 'brindisi', provincia: 'Brindisi', regione: 'Puglia' },
  { nome: 'Cagliari', slug: 'cagliari', provincia: 'Cagliari', regione: 'Sardegna' },
  { nome: 'Caltanissetta', slug: 'caltanissetta', provincia: 'Caltanissetta', regione: 'Sicilia' },
  { nome: 'Campobasso', slug: 'campobasso', provincia: 'Campobasso', regione: 'Molise' },
  { nome: 'Carbonia', slug: 'carbonia', provincia: 'Sud Sardegna', regione: 'Sardegna' },
  { nome: 'Caserta', slug: 'caserta', provincia: 'Caserta', regione: 'Campania' },
  { nome: 'Catania', slug: 'catania', provincia: 'Catania', regione: 'Sicilia' },
  { nome: 'Catanzaro', slug: 'catanzaro', provincia: 'Catanzaro', regione: 'Calabria' },
  { nome: 'Chieti', slug: 'chieti', provincia: 'Chieti', regione: 'Abruzzo' },
  { nome: 'Como', slug: 'como', provincia: 'Como', regione: 'Lombardia' },
  { nome: 'Cosenza', slug: 'cosenza', provincia: 'Cosenza', regione: 'Calabria' },
  { nome: 'Cremona', slug: 'cremona', provincia: 'Cremona', regione: 'Lombardia' },
  { nome: 'Crotone', slug: 'crotone', provincia: 'Crotone', regione: 'Calabria' },
  { nome: 'Cuneo', slug: 'cuneo', provincia: 'Cuneo', regione: 'Piemonte' },
  { nome: 'Enna', slug: 'enna', provincia: 'Enna', regione: 'Sicilia' },
  { nome: 'Fermo', slug: 'fermo', provincia: 'Fermo', regione: 'Marche' },
  { nome: 'Ferrara', slug: 'ferrara', provincia: 'Ferrara', regione: 'Emilia-Romagna' },
  {
    nome: 'Firenze',
    slug: 'firenze',
    provincia: 'Firenze',
    regione: 'Toscana',
    intro: 'A Firenze, tra il lavoro e i ritmi della città, prenderti cura della tua salute mentale deve essere semplice: con le sedute online di Adatto x Te lo è, senza attese né spostamenti.',
    faqExtra: [
      ['Come scelgo lo psicologo giusto per me a Firenze?', 'Confronti i profili verificati dei terapeuti (specializzazioni, recensioni, lingue) e prenoti in autonomia l\'orario che preferisci.'],
      ['Le sedute sono disponibili anche in inglese?', 'Sì: Adatto x Te offre sedute anche in inglese, francese e spagnolo, utili per chi vive a Firenze o lavora in contesti internazionali.'],
    ],
  },
  { nome: 'Foggia', slug: 'foggia', provincia: 'Foggia', regione: 'Puglia' },
  { nome: 'Forlì', slug: 'forli', provincia: 'Forlì-Cesena', regione: 'Emilia-Romagna' },
  { nome: 'Frosinone', slug: 'frosinone', provincia: 'Frosinone', regione: 'Lazio' },
  {
    nome: 'Genova',
    slug: 'genova',
    provincia: 'Genova',
    regione: 'Liguria',
    intro: 'A Genova, tra gli impegni di lavoro e gli spostamenti della città, trovare il momento giusto per la terapia è più facile con le sedute online di Adatto x Te: prenoti e ti colleghi quando vuoi.',
    faqExtra: [
      ['Come funziona la prenotazione a Genova?', 'Registrati gratuitamente, scegli il terapeuta e l\'orario tra gli slot disponibili e paga online: la prenotazione richiede pochi minuti.'],
      ['Posso cancellare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto, senza complicazioni.'],
    ],
  },
  { nome: 'Gorizia', slug: 'gorizia', provincia: 'Gorizia', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Grosseto', slug: 'grosseto', provincia: 'Grosseto', regione: 'Toscana' },
  { nome: 'Imperia', slug: 'imperia', provincia: 'Imperia', regione: 'Liguria' },
  { nome: 'Isernia', slug: 'isernia', provincia: 'Isernia', regione: 'Molise' },
  { nome: 'L\'Aquila', slug: 'l-aquila', provincia: 'L\'Aquila', regione: 'Abruzzo' },
  { nome: 'La Spezia', slug: 'la-spezia', provincia: 'La Spezia', regione: 'Liguria' },
  { nome: 'Latina', slug: 'latina', provincia: 'Latina', regione: 'Lazio' },
  { nome: 'Lecce', slug: 'lecce', provincia: 'Lecce', regione: 'Puglia' },
  { nome: 'Lecco', slug: 'lecco', provincia: 'Lecco', regione: 'Lombardia' },
  { nome: 'Livorno', slug: 'livorno', provincia: 'Livorno', regione: 'Toscana' },
  { nome: 'Lodi', slug: 'lodi', provincia: 'Lodi', regione: 'Lombardia' },
  { nome: 'Lucca', slug: 'lucca', provincia: 'Lucca', regione: 'Toscana' },
  { nome: 'Macerata', slug: 'macerata', provincia: 'Macerata', regione: 'Marche' },
  { nome: 'Mantova', slug: 'mantova', provincia: 'Mantova', regione: 'Lombardia' },
  { nome: 'Massa', slug: 'massa', provincia: 'Massa-Carrara', regione: 'Toscana' },
  { nome: 'Matera', slug: 'matera', provincia: 'Matera', regione: 'Basilicata' },
  { nome: 'Messina', slug: 'messina', provincia: 'Messina', regione: 'Sicilia' },
  {
    nome: 'Milano',
    slug: 'milano',
    provincia: 'Milano',
    regione: 'Lombardia',
    intro: 'A Milano i ritmi di lavoro e la pressione quotidiana lasciano poco spazio al benessere: con la terapia online non devi incastrare spostamenti o orari di uno studio, prenoti la seduta quando sei libero, anche la sera dopo il lavoro.',
    faqExtra: [
      ['Posso prenotare la sera o nel weekend, dopo il lavoro a Milano?', 'Sì: su Adatto x Te trovi orari flessibili, con sedute anche la sera e nel weekend, pensate per chi vive a Milano e ha una giornata piena.'],
      ['Devo andare in uno studio a Milano per la prima seduta?', 'No: tutto avviene in videochiamata sicura, da casa o dall\'ufficio. Il servizio copre Milano e tutta la provincia, senza spostamenti.'],
    ],
  },
  { nome: 'Modena', slug: 'modena', provincia: 'Modena', regione: 'Emilia-Romagna' },
  { nome: 'Monza', slug: 'monza', provincia: 'Monza e Brianza', regione: 'Lombardia' },
  {
    nome: 'Napoli',
    slug: 'napoli',
    provincia: 'Napoli',
    regione: 'Campania',
    intro: 'A Napoli e in tutta la provincia, la terapia online ti permette di iniziare un percorso senza dipendere dagli orari di uno studio o dagli spostamenti: scegli tu quando e da dove collegarti.',
    faqExtra: [
      ['È possibile parlare con uno psicologo online restando anonimi?', 'Sì: il catalogo è anonimo e il nome del terapeuta viene mostrato solo dopo la prenotazione, per garantire la massima riservatezza.'],
      ['Posso fare terapia di coppia online da Napoli?', 'Sì: la seduta di coppia costa 50€ e si svolge in videochiamata, comoda anche quando i partner vivono in città diverse.'],
    ],
  },
  { nome: 'Novara', slug: 'novara', provincia: 'Novara', regione: 'Piemonte' },
  { nome: 'Nuoro', slug: 'nuoro', provincia: 'Nuoro', regione: 'Sardegna' },
  { nome: 'Oristano', slug: 'oristano', provincia: 'Oristano', regione: 'Sardegna' },
  { nome: 'Padova', slug: 'padova', provincia: 'Padova', regione: 'Veneto' },
  {
    nome: 'Palermo',
    slug: 'palermo',
    provincia: 'Palermo',
    regione: 'Sicilia',
    intro: 'A Palermo, come nel resto della Sicilia, la psicologia online elimina le barriere geografiche: bastano una connessione e un dispositivo per iniziare un percorso con professionisti qualificati.',
    faqExtra: [
      ['Vivo in provincia di Palermo: posso accedere al servizio?', 'Sì, il servizio è completamente online e copre tutta la provincia e la regione: non serve recarsi in uno studio.'],
      ['Quali sono i prezzi a Palermo?', 'I prezzi sono nazionali e trasparenti: 45€ la seduta individuale, 50€ quella di coppia, pagamento sicuro online.'],
    ],
  },
  { nome: 'Parma', slug: 'parma', provincia: 'Parma', regione: 'Emilia-Romagna' },
  { nome: 'Pavia', slug: 'pavia', provincia: 'Pavia', regione: 'Lombardia' },
  { nome: 'Perugia', slug: 'perugia', provincia: 'Perugia', regione: 'Umbria' },
  { nome: 'Pesaro', slug: 'pesaro', provincia: 'Pesaro-Urbino', regione: 'Marche' },
  { nome: 'Pescara', slug: 'pescara', provincia: 'Pescara', regione: 'Abruzzo' },
  { nome: 'Piacenza', slug: 'piacenza', provincia: 'Piacenza', regione: 'Emilia-Romagna' },
  { nome: 'Pisa', slug: 'pisa', provincia: 'Pisa', regione: 'Toscana' },
  { nome: 'Pistoia', slug: 'pistoia', provincia: 'Pistoia', regione: 'Toscana' },
  { nome: 'Pordenone', slug: 'pordenone', provincia: 'Pordenone', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Potenza', slug: 'potenza', provincia: 'Potenza', regione: 'Basilicata' },
  { nome: 'Prato', slug: 'prato', provincia: 'Prato', regione: 'Toscana' },
  { nome: 'Ragusa', slug: 'ragusa', provincia: 'Ragusa', regione: 'Sicilia' },
  { nome: 'Ravenna', slug: 'ravenna', provincia: 'Ravenna', regione: 'Emilia-Romagna' },
  { nome: 'Reggio Calabria', slug: 'reggio-calabria', provincia: 'Reggio Calabria', regione: 'Calabria' },
  { nome: 'Reggio Emilia', slug: 'reggio-emilia', provincia: 'Reggio Emilia', regione: 'Emilia-Romagna' },
  { nome: 'Rieti', slug: 'rieti', provincia: 'Rieti', regione: 'Lazio' },
  { nome: 'Rimini', slug: 'rimini', provincia: 'Rimini', regione: 'Emilia-Romagna' },
  {
    nome: 'Roma',
    slug: 'roma',
    provincia: 'Roma',
    regione: 'Lazio',
    intro: 'A Roma lo stress da traffico, i tempi lunghi degli spostamenti e la pressione di studio e concorsi pubblici mettono a dura prova: con Adatto x Te la seduta è in videochiamata, senza code né attese, ovunque tu sia nella capitale.',
    faqExtra: [
      ['Preparo un concorso pubblico a Roma: mi potete aiutare?', 'Sì: su Adatto x Te trovi psicologi specializzati in preparazione ai concorsi, con supporto per ansia da prestazione e gestione dello stress.'],
      ['Le sedute online a Roma funzionano bene?', 'Sì: la terapia online ha la stessa efficacia di quella in presenza ed eviti i tempi di spostamento nella città. Ti colleghi da dove preferisci.'],
    ],
  },
  { nome: 'Rovigo', slug: 'rovigo', provincia: 'Rovigo', regione: 'Veneto' },
  { nome: 'Salerno', slug: 'salerno', provincia: 'Salerno', regione: 'Campania' },
  { nome: 'Sassari', slug: 'sassari', provincia: 'Sassari', regione: 'Sardegna' },
  { nome: 'Savona', slug: 'savona', provincia: 'Savona', regione: 'Liguria' },
  { nome: 'Siena', slug: 'siena', provincia: 'Siena', regione: 'Toscana' },
  { nome: 'Siracusa', slug: 'siracusa', provincia: 'Siracusa', regione: 'Sicilia' },
  { nome: 'Sondrio', slug: 'sondrio', provincia: 'Sondrio', regione: 'Lombardia' },
  { nome: 'Taranto', slug: 'taranto', provincia: 'Taranto', regione: 'Puglia' },
  { nome: 'Teramo', slug: 'teramo', provincia: 'Teramo', regione: 'Abruzzo' },
  { nome: 'Terni', slug: 'terni', provincia: 'Terni', regione: 'Umbria' },
  {
    nome: 'Torino',
    slug: 'torino',
    provincia: 'Torino',
    regione: 'Piemonte',
    intro: 'A Torino, tra lavoro e famiglia, trovare il tempo per prendersi cura di sé non è semplice: le sedute online di Adatto x Te si adattano ai tuoi orari, senza spostamenti per la città.',
    faqExtra: [
      ['Quanto costa una seduta di psicologia online a Torino?', 'La seduta individuale costa 45€, quella di coppia 50€, con sconto del 15% sul pacchetto di 3 sedute. Paghi online in modo sicuro.'],
      ['Come funziona la videochiamata?', 'Ti colleghi al link della seduta direttamente dal browser, con Jitsi: nessuna installazione, bastano un dispositivo e una connessione stabile.'],
    ],
  },
  { nome: 'Trani', slug: 'trani', provincia: 'Barletta-Andria-Trani', regione: 'Puglia' },
  { nome: 'Trapani', slug: 'trapani', provincia: 'Trapani', regione: 'Sicilia' },
  { nome: 'Trento', slug: 'trento', provincia: 'Trento', regione: 'Trentino-Alto Adige' },
  { nome: 'Treviso', slug: 'treviso', provincia: 'Treviso', regione: 'Veneto' },
  { nome: 'Trieste', slug: 'trieste', provincia: 'Trieste', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Udine', slug: 'udine', provincia: 'Udine', regione: 'Friuli-Venezia Giulia' },
  { nome: 'Urbino', slug: 'urbino', provincia: 'Pesaro-Urbino', regione: 'Marche' },
  { nome: 'Varese', slug: 'varese', provincia: 'Varese', regione: 'Lombardia' },
  {
    nome: 'Venezia',
    slug: 'venezia',
    provincia: 'Venezia',
    regione: 'Veneto',
    intro: 'A Venezia e nella terraferma, raggiungere uno studio richiede spesso tragitti lunghi e costosi: con Adatto x Te la seduta è in videochiamata, anche solo per 50 minuti, da casa o dall\'ufficio.',
    faqExtra: [
      ['Posso fare terapia online vivendo in un\'isola o nella terraferma di Venezia?', 'Sì, il servizio è online e funziona ovunque: ti serve solo una connessione stabile, senza spostamenti in vaporetto o in auto.'],
      ['Come pago la seduta?', 'Il pagamento è online e sicuro con PayPal o carta: 45€ individuale, 50€ di coppia, sconto 15% sul pacchetto di 3 sedute.'],
    ],
  },
  { nome: 'Verbania', slug: 'verbania', provincia: 'Verbano-Cusio-Ossola', regione: 'Piemonte' },
  { nome: 'Vercelli', slug: 'vercelli', provincia: 'Vercelli', regione: 'Piemonte' },
  { nome: 'Verona', slug: 'verona', provincia: 'Verona', regione: 'Veneto' },
  { nome: 'Vibo Valentia', slug: 'vibo-valentia', provincia: 'Vibo Valentia', regione: 'Calabria' },
  { nome: 'Vicenza', slug: 'vicenza', provincia: 'Vicenza', regione: 'Veneto' },
  { nome: 'Viterbo', slug: 'viterbo', provincia: 'Viterbo', regione: 'Lazio' },
];
