// Capoluoghi di provincia italiani per le pagine "psicologo online [città]".
// Il servizio è online da tutta Italia: le pagine catturano la ricerca locale.
// Struttura: { nome, slug, provincia, regione }

// Città con contenuto differenziato: le uniche indicizzate (le altre sono noindex
// per evitare doorway pages / thin content). Lista basata sui volumi di ricerca.
export const CITTA_TOP = [
  'milano', 'roma', 'napoli', 'torino', 'bari', 'bologna', 'firenze',
  'verona', 'palermo', 'genova', 'padova', 'catania', 'bergamo', 'brescia', 'cagliari',
];

export const citta = [
    {
    nome: 'Agrigento',
    slug: 'agrigento',
    provincia: 'Agrigento',
    regione: 'Sicilia',
    intro: 'Tra la Valle dei Templi e il mare, Agrigento ha ritmi e distanze che non sempre lasciano spazio al benessere. La terapia online ti raggiunge a casa o ovunque tu sia: prenoti in 2 minuti e scegli tu l\'orario.',
    faqExtra: [
      ['Devo vivere a Agrigento per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Agrigento o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Alessandria',
    slug: 'alessandria',
    provincia: 'Alessandria',
    regione: 'Piemonte',
    intro: 'Alessandria è un punto di passaggio tra Torino, Milano e Genova: tra pendolarismo e lavoro, trovare il tempo per uno psicologo è più facile con le sedute online, senza spostamenti.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'Ancona',
    slug: 'ancona',
    provincia: 'Ancona',
    regione: 'Marche',
    intro: 'Capoluogo delle Marche, Ancona vive tra porto, colline e spostamenti: con Adatto x Te il supporto psicologico arriva in videochiamata, anche per chi lavora o studia lontano da casa.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Ancona?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Aosta',
    slug: 'aosta',
    provincia: 'Aosta',
    regione: 'Valle d\\\'Aosta',
    intro: 'Nella regione più piccola d\'Italia, raggiungere uno studio può significare chilometri e montagna in mezzo: la terapia online elimina il viaggio e garantisce continuità anche d\'inverno.',
    faqExtra: [
      ['Devo vivere ad Aosta per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi ad Aosta o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Arezzo',
    slug: 'arezzo',
    provincia: 'Arezzo',
    regione: 'Toscana',
    intro: 'Ad Arezzo, tra il centro storico e le vallate, la psicologia online porta la stessa qualità di uno studio direttamente a casa tua, con orari che rispettano la tua giornata.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
    {
    nome: 'Ascoli Piceno',
    slug: 'ascoli-piceno',
    provincia: 'Ascoli Piceno',
    regione: 'Marche',
    intro: 'Ad Ascoli Piceno la vita scorre tra lavoro e famiglia: le sedute in videochiamata ti permettono di iniziare o continuare un percorso senza spostamenti, in tutta la provincia.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Asti',
    slug: 'asti',
    provincia: 'Asti',
    regione: 'Piemonte',
    intro: 'Asti e le sue colline del Monferrato: per chi vive in provincia raggiungere un terapeuta richiede tempo. Online ti colleghi in un clic, dal divano o dall\'ufficio.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Asti?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Avellino',
    slug: 'avellino',
    provincia: 'Avellino',
    regione: 'Campania',
    intro: 'Tra i monti dell\'Irpinia e i pendolari verso Napoli, Avellino ha bisogno di servizi flessibili: con la terapia online prenoti quando sei libero e ti colleghi da dove sei.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Avellino per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Avellino o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
  {
    nome: 'Bari',
    slug: 'bari',
    provincia: 'Bari',
    regione: 'Puglia',
    intro: 'A Bari e in tutta la Puglia, la terapia online rende il supporto psicologico accessibile anche a chi ha orari difficili o vive lontano dai centri: prenoti, paghi e ti colleghi in videochiamata.',
    local: `<h3>Psicologo online a Bari: senza spostamenti né attese</h3><p>A Bari i prezzi in studio partono da circa <strong>50-70 euro</strong>, e per chi abita in provincia (Molfetta, Bitonto, Monopoli, Putignano) ogni seduta significa un viaggio. Con Adatto x Te la seduta costa <strong>45 euro</strong> e basta un telefono: niente traffico, niente parcheggio, niente code in sala d'attesa.</p><p>Un aiuto concreto per chi lavora nel commercio o nella sanità, per gli studenti universitari e per chi vive nei comuni costieri o dell'entroterra.</p>`,
    faqExtra: [
      ['Quali specialisti sono disponibili per chi vive a Bari?', 'Trovi psicologi per ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: confronta i profili e scegli.'],
      ['Posso scrivere al terapeuta tra una seduta e l\'altra?', 'Sì, su Adatto x Te i messaggi con il terapeuta sono illimitati: puoi restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Barletta',
    slug: 'barletta',
    provincia: 'Barletta-Andria-Trani',
    regione: 'Puglia',
    intro: 'Barletta, tra la BAT e la costa adriatica: la terapia online elimina gli spostamenti verso le città più grandi e rende il supporto psicologico accessibile a tutta la provincia.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Belluno',
    slug: 'belluno',
    provincia: 'Belluno',
    regione: 'Veneto',
    intro: 'Nel cuore delle Dolomiti, Belluno ha centri abitati distanti tra loro: la videochiamata porta il terapeuta ovunque, anche nei comuni più piccoli della provincia.',
    faqExtra: [
      ['Come scelgo il terapeuta a Belluno?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Belluno?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Benevento',
    slug: 'benevento',
    provincia: 'Benevento',
    regione: 'Campania',
    intro: 'Benevento, crocevia tra Campania, Puglia e Molise: per chi vive in provincia il percorso online evita il viaggio e garantisce costanza, con sedute anche di sera.',
    faqExtra: [
      ['Devo vivere a Benevento per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Benevento o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
  {
    nome: 'Bergamo',
    slug: 'bergamo',
    provincia: 'Bergamo',
    regione: 'Lombardia',
    intro: 'A Bergamo, tra gli spostamenti tra città bassa e città alta e i ritmi di chi lavora verso Milano, trovare il tempo per la terapia è più facile con le sedute online: prenoti e ti colleghi da dove sei.',
    local: `<h3>Psicologo online a Bergamo: la scelta di chi fa il pendolare</h3><p>Bergamo vive di pendolarismo: migliaia di persone si spostano ogni giorno verso Milano o dentro la provincia (Dalmine, Treviglio, Seriate, Romano). Tra treni e orari, la seduta in studio (in media <strong>55-80 euro</strong>) diventa difficile da organizzare; online costa <strong>45 euro</strong> e non dipende dagli spostamenti.</p><p>Ideale per chi lavora nella logistica o nell'industria della bassa, per i pendolari Milano-Bergamo e per chi vive nei paesi della Val Brembana o della Val Seriana.</p>`,
    faqExtra: [
      ['Vivo tra Bergamo e Milano: posso prenotare da entrambe le città?', 'Sì, il servizio è completamente online: ti colleghi da dove ti trovi, ti serve solo una connessione stabile e un dispositivo.'],
      ['Come funziona la prima prenotazione?', 'Ti registri, confronti i profili dei terapeuti, scegli l\'orario e paghi online: 45€ la seduta individuale, 50€ quella di coppia, con sconto del 15% sul pacchetto di 3 sedute.'],
    ],
  },
    {
    nome: 'Biella',
    slug: 'biella',
    provincia: 'Biella',
    regione: 'Piemonte',
    intro: 'Tra le Prealpi biellesi e la pianura, Biella offre un servizio di psicologia online comodo e discreto: prenoti, paghi e ti colleghi in videochiamata sicura.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
  {
    nome: 'Bologna',
    slug: 'bologna',
    provincia: 'Bologna',
    regione: 'Emilia-Romagna',
    intro: 'A Bologna, città universitaria per eccellenza, ansia da esame e pressione degli studi sono tra i motivi più comuni per iniziare un percorso: con Adatto x Te trovi supporto specializzato senza spostarti dalla scrivania.',
    local: `<h3>Psicologo online a Bologna: la flessibilità che serve agli studenti e a chi lavora</h3><p>Bologna è una città universitaria con ritmi intensi: tra esami, stage e lavoro, trovare lo spazio per la terapia in presenza non è scontato, e lo studio in centro costa in media <strong>55-80 euro</strong>. Online la seduta costa <strong>45 euro</strong> e puoi collegarti da casa, dall'aula studio o in pausa.</p><p>Il modello è particolarmente adatto a studenti fuori sede e a chi lavora nei servizi o nella logistica dell'Emilia, dove gli orari non sempre coincidono con quelli degli studi tradizionali.</p>`,
    faqExtra: [
      ['Sono uno studente universitario a Bologna: posso prenotare sedute tra un esame e l\'altro?', 'Certo: prenoti online l\'orario che preferisci, anche con pochi giorni di anticipo, e annulli o sposti la seduta senza complicazioni.'],
      ['Esistono sconti per i pacchetti?', 'Sì: il pacchetto di 3 sedute ha uno sconto del 15%, così il percorso continuativo costa meno della singola seduta.'],
    ],
  },
    {
    nome: 'Bolzano',
    slug: 'bolzano',
    provincia: 'Bolzano',
    regione: 'Trentino-Alto Adige',
    intro: 'A Bolzano, tra lingua italiana e tedesca, la piattaforma è disponibile anche in inglese: il supporto psicologico online supera le distanze della valle e della provincia.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Bolzano?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
  {
    nome: 'Brescia',
    slug: 'brescia',
    provincia: 'Brescia',
    regione: 'Lombardia',
    intro: 'A Brescia, tra lavoro, famiglia e gli spostamenti tra la città e la provincia, la terapia online elimina gli ostacoli: una seduta di 50 minuti in videochiamata, quando funziona a te.',
    local: `<h3>Psicologo online a Brescia: flessibilità per ritmi industriali</h3><p>Brescia e la sua provincia sono un territorio industriale dove gli orari di lavoro sono spesso rigidi (turni in fabbrica, PMI, logistica). La seduta in studio costa in media <strong>55-80 euro</strong>; online <strong>45 euro</strong> e si organizza attorno ai tuoi turni, anche la sera.</p><p>Una soluzione adatta a chi lavora nell'industria o nei servizi, a chi vive nei comuni della Franciacorta o della Valtrompia e a chi fa fatica a trovare uno spazio nella giornata.</p>`,
    faqExtra: [
      ['Faccio orari di lavoro intensi: trovo slot anche la sera?', 'Sì, su Adatto x Te gli orari sono flessibili e puoi prenotare la seduta nell\'orario che preferisci, anche la sera o nel weekend.'],
      ['Quali problemi posso affrontare online?', 'Ansia, stress, depressione, terapia di coppia, psicologia dello sport e preparazione ai concorsi: confronta i profili e scegli lo specialista più adatto.'],
    ],
  },
    {
    nome: 'Brindisi',
    slug: 'brindisi',
    provincia: 'Brindisi',
    regione: 'Puglia',
    intro: 'Brindisi, porta d\'Oriente tra porto e mare: la terapia online è la scelta giusta per chi ha orari intensi e non vuole rinunciare al supporto psicologico.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
  {
    nome: 'Cagliari',
    slug: 'cagliari',
    provincia: 'Cagliari',
    regione: 'Sardegna',
    intro: 'A Cagliari e in tutta la Sardegna, dove le distanze e i collegamenti con il resto della penisola complicano gli spostamenti, la terapia online rende il supporto psicologico accessibile a tutti, senza viaggi né attese.',
    local: `<h3>Psicologo online a Cagliari: continuità anche tra l'isola e il continente</h3><p>A Cagliari una seduta in studio costa in media <strong>50-75 euro</strong>, con gli spostamenti tipici di una città che si allunga lungo il mare (da Quartu al Poetto fino a Elmas e Selargius). Online la seduta costa <strong>45 euro</strong> e funziona ovunque: in città, in provincia o anche fuori dalla Sardegna.</p><p>La continuità del percorso è il vero vantaggio: chi studia o lavora tra Cagliari e il continente (Roma, Milano, Torino) non deve mai interrompere la terapia.</p>`,
    faqExtra: [
      ['Vivo in un paese dell\'interno della Sardegna: posso accedere?', 'Certo: il servizio è online da tutta la Sardegna, ti serve solo una connessione stabile. Nessuno spostamento necessario.'],
      ['Quali sono i prezzi?', 'Prezzi nazionali trasparenti: 45€ a seduta individuale, 50€ di coppia, sconto 15% sul pacchetto di 3 sedute, pagamento sicuro online.'],
    ],
  },
    {
    nome: 'Caltanissetta',
    slug: 'caltanissetta',
    provincia: 'Caltanissetta',
    regione: 'Sicilia',
    intro: 'Nel cuore della Sicilia, Caltanissetta è lontana dai grandi centri: con le sedute online hai un terapeuta qualificato senza percorrere chilometri.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
    {
    nome: 'Campobasso',
    slug: 'campobasso',
    provincia: 'Campobasso',
    regione: 'Molise',
    intro: 'Campobasso è il capoluogo di una regione fatta di borghi e distanze: la psicologia online porta il benessere ovunque, anche nei piccoli comuni del Molise.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Carbonia',
    slug: 'carbonia',
    provincia: 'Sud Sardegna',
    regione: 'Sardegna',
    intro: 'Nel Sulcis, tra storia mineraria e nuove economie, Carbonia trova nella terapia online un supporto accessibile: prenoti e ti colleghi da casa, senza spostamenti.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Carbonia?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Caserta',
    slug: 'caserta',
    provincia: 'Caserta',
    regione: 'Campania',
    intro: 'Caserta, tra la Reggia e il pendolarismo verso Napoli: la seduta online si adatta ai tuoi orari e ti evita code e spostamenti quotidiani.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Caserta per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Caserta o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
  {
    nome: 'Catania',
    slug: 'catania',
    provincia: 'Catania',
    regione: 'Sicilia',
    intro: 'A Catania, tra i ritmi della città e le distanze della provincia etnea, iniziare un percorso psicologico online ti permette di ricevere supporto da casa, senza dipendere da orari di studio o spostamenti.',
    local: `<h3>Psicologo online a Catania: un percorso su misura per il territorio</h3><p>Nell'area metropolitana etnea, tra la città e i comuni della provincia (Acireale, Paternò, Misterbianco, Gravina), ogni seduta in studio comporta uno spostamento. I prezzi in presenza partono da <strong>50-70 euro</strong>; online la seduta costa <strong>45 euro</strong> e la fai da casa, in qualsiasi orario.</p><p>Una soluzione pensata per chi lavora nel commercio o nei servizi con orari lunghi, per gli studenti e per chi preferisce iniziare un percorso nella massima riservatezza.</p>`,
    faqExtra: [
      ['Sono uno studente universitario a Catania: posso prenotare tra gli esami?', 'Sì, prenoti online l\'orario che preferisci e puoi annullare o spostare la seduta senza complicazioni prima dell\'orario previsto.'],
      ['Posso fare terapia di coppia online?', 'Sì, la seduta di coppia costa 50€ e si svolge in videochiamata, comoda anche se i partner vivono in città diverse.'],
    ],
  },
    {
    nome: 'Catanzaro',
    slug: 'catanzaro',
    provincia: 'Catanzaro',
    regione: 'Calabria',
    intro: 'Catanzaro, il ponte tra due mari: la terapia online supera le distanze calabresi e offre continuità a chi vive tra città e provincia.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Chieti',
    slug: 'chieti',
    provincia: 'Chieti',
    regione: 'Abruzzo',
    intro: 'Chieti, tra mare e montagna: il supporto psicologico in videochiamata è ideale per chi lavora, studia o vive nei comuni della provincia teatina.',
    faqExtra: [
      ['Come scelgo il terapeuta a Chieti?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Chieti?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Como',
    slug: 'como',
    provincia: 'Como',
    regione: 'Lombardia',
    intro: 'Como e il suo lago: per chi vive sul lago o lavora a Milano, la terapia online elimina gli spostamenti e garantisce flessibilità totale di orario.',
    faqExtra: [
      ['Devo vivere a Como per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Como o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Cosenza',
    slug: 'cosenza',
    provincia: 'Cosenza',
    regione: 'Calabria',
    intro: 'Cosenza e la Sibaritide, tra il Pollino e la Sila: la videochiamata porta il supporto psicologico ovunque, anche nei comuni più remoti della provincia.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'Cremona',
    slug: 'cremona',
    provincia: 'Cremona',
    regione: 'Lombardia',
    intro: 'Cremona, città della musica e della pianura: con la terapia online hai sedute comode e riservate, senza lasciare casa o ufficio.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Cremona?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Crotone',
    slug: 'crotone',
    provincia: 'Crotone',
    regione: 'Calabria',
    intro: 'Crotone, tra il mare e la provincia pitagorica: la terapia online elimina gli spostamenti e porta il supporto psicologico a casa tua, in tutta la zona.',
    faqExtra: [
      ['Devo vivere a Crotone per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Crotone o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Come scelgo il terapeuta?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Cuneo',
    slug: 'cuneo',
    provincia: 'Cuneo',
    regione: 'Piemonte',
    intro: 'Cuneo e le sue valli alpine: per chi vive nei borghi di montagna, la psicologia online evita il viaggio in città e garantisce regolarità.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
    {
    nome: 'Enna',
    slug: 'enna',
    provincia: 'Enna',
    regione: 'Sicilia',
    intro: 'Enna, il cuore della Sicilia tra le montagne: per chi vive nei paesi dell\'entroterra, la videochiamata porta il terapeuta ovunque, senza chilometri.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Fermo',
    slug: 'fermo',
    provincia: 'Fermo',
    regione: 'Marche',
    intro: 'Fermo, tra colline e mare: il percorso online si adatta alla tua vita, con sedute da 50 minuti in videochiamata sicura.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
    {
    nome: 'Ferrara',
    slug: 'ferrara',
    provincia: 'Ferrara',
    regione: 'Emilia-Romagna',
    intro: 'Ferrara, tra il Po e l\'Estense: la psicologia online rispetta i tuoi tempi, con sedute comode da casa o dall\'ufficio.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Ferrara?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
  {
    nome: 'Firenze',
    slug: 'firenze',
    provincia: 'Firenze',
    regione: 'Toscana',
    intro: 'A Firenze, tra il lavoro e i ritmi della città, prenderti cura della tua salute mentale deve essere semplice: con le sedute online di Adatto x Te lo è, senza attese né spostamenti.',
    local: `<h3>Psicologo online a Firenze: più tempo per te, meno tempo in centro</h3><p>A Firenze raggiungere uno studio significa fare i conti con ztl, traffico e parcheggi: una spesa di tempo e denaro che si somma al costo della seduta (in media <strong>60-90 euro</strong> in centro). La terapia online a <strong>45 euro</strong> elimina il problema: ti colleghi da casa, senza spostarti.</p><p>Ideale per chi lavora nel turismo e nella ristorazione (orari serali compresi), per chi abita nelle colline o nei comuni del Chianti e per i professionisti con agende piene.</p>`,
    faqExtra: [
      ['Come scelgo lo psicologo giusto per me a Firenze?', 'Confronti i profili verificati dei terapeuti (specializzazioni, recensioni, lingue) e prenoti in autonomia l\'orario che preferisci.'],
      ['Le sedute sono disponibili anche in inglese?', 'Sì: Adatto x Te offre sedute anche in inglese, francese e spagnolo, utili per chi vive a Firenze o lavora in contesti internazionali.'],
    ],
  },
    {
    nome: 'Foggia',
    slug: 'foggia',
    provincia: 'Foggia',
    regione: 'Puglia',
    intro: 'Foggia, capoluogo della Capitanata: tra pianura e Tavoliere, la terapia online rende il supporto psicologico accessibile senza spostamenti.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Forlì',
    slug: 'forli',
    provincia: 'Forlì-Cesena',
    regione: 'Emilia-Romagna',
    intro: 'A Forlì il benessere passa dal divano di casa: sedute in videochiamata con terapeuti qualificati, orari flessibili, prenotazione in 2 minuti.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Forlì?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Frosinone',
    slug: 'frosinone',
    provincia: 'Frosinone',
    regione: 'Lazio',
    intro: 'Frosinone, tra Roma e la Ciociaria: per i pendolari e chi vive in provincia, la seduta online è la soluzione per non rinunciare alla terapia.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Frosinone per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Frosinone o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
  {
    nome: 'Genova',
    slug: 'genova',
    provincia: 'Genova',
    regione: 'Liguria',
    intro: 'A Genova, tra gli impegni di lavoro e gli spostamenti della città, trovare il momento giusto per la terapia è più facile con le sedute online di Adatto x Te: prenoti e ti colleghi quando vuoi.',
    local: `<h3>Psicologo online a Genova: la terapia che arriva anche in valle</h3><p>A Genova la conformazione della città (lunga e stretta tra il mare e l'entroterra) rende lunghi anche i tragitti brevi sulla mappa: spostarsi tra quartieri o dalla Val Polcevera e dalla Val Bisagno richiede tempo. La seduta in studio costa in media <strong>55-80 euro</strong>; online <strong>45 euro</strong>, da casa.</p><p>Perfetta per chi lavora nel porto e nella logistica con turni irregolari, per i pendolari e per chi vive in provincia o nelle vallate.</p>`,
    faqExtra: [
      ['Come funziona la prenotazione a Genova?', 'Registrati gratuitamente, scegli il terapeuta e l\'orario tra gli slot disponibili e paga online: la prenotazione richiede pochi minuti.'],
      ['Posso cancellare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto, senza complicazioni.'],
    ],
  },
    {
    nome: 'Gorizia',
    slug: 'gorizia',
    provincia: 'Gorizia',
    regione: 'Friuli-Venezia Giulia',
    intro: 'Gorizia, città di confine: la terapia online supera i confini e le distanze, offrendo supporto psicologico a chi vive tra Italia e Slovenia.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Grosseto',
    slug: 'grosseto',
    provincia: 'Grosseto',
    regione: 'Toscana',
    intro: 'Grosseto, tra la Maremma e il mare: il supporto psicologico online è accessibile a tutta la provincia, anche nei borghi più lontani.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
    {
    nome: 'Imperia',
    slug: 'imperia',
    provincia: 'Imperia',
    regione: 'Liguria',
    intro: 'Imperia, tra ponente ligure e Riviera: con la videochiamata il supporto psicologico ti raggiunge a casa, anche nei comuni della costa.',
    faqExtra: [
      ['Come scelgo il terapeuta a Imperia?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Imperia?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Isernia',
    slug: 'isernia',
    provincia: 'Isernia',
    regione: 'Molise',
    intro: 'Isernia, nel cuore del Molise: per chi vive nei comuni della provincia, la terapia online evita chilometri e garantisce continuità.',
    faqExtra: [
      ['Devo vivere a Isernia per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Isernia o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'L\\\'Aquila',
    slug: 'l-aquila',
    provincia: 'L\\\'Aquila',
    regione: 'Abruzzo',
    intro: 'L\'Aquila, tra le montagne abruzzesi: una città che sta ricostruendo se stessa ha bisogno di benessere: la psicologia online è accessibile e discreta.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'La Spezia',
    slug: 'la-spezia',
    provincia: 'La Spezia',
    regione: 'Liguria',
    intro: 'La Spezia, tra porto e Cinque Terre: il supporto psicologico in videochiamata si adatta a turni e impegni, anche per chi vive sul golfo.',
    faqExtra: [
      ['Quali percorsi sono disponibili a La Spezia?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Latina',
    slug: 'latina',
    provincia: 'Latina',
    regione: 'Lazio',
    intro: 'Latina, tra l\'Agro Pontino e il mare: la terapia online offre sedute comode e flessibili, senza spostarti in città.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
  {
    nome: 'Lecce',
    slug: 'lecce',
    provincia: 'Lecce',
    regione: 'Puglia',
    intro: 'Nel Salento, tra le distanze della provincia e i ritmi della vita di tutti i giorni, la terapia online di Adatto x Te porta il supporto psicologico direttamente a casa tua: bastano un dispositivo e una connessione.',
    faqExtra: [
      ['Vivo in provincia di Lecce: il servizio è disponibile?', 'Sì, il servizio è completamente online e copre tutto il territorio: non devi spostarti per raggiungere uno studio.'],
      ['Come scelgo lo psicologo giusto?', 'Confronti i profili verificati dei terapeuti, con specializzazione, esperienza e recensioni, e prenoti in autonomia l\'orario che preferisci.'],
    ],
  },
    {
    nome: 'Lecco',
    slug: 'lecco',
    provincia: 'Lecco',
    regione: 'Lombardia',
    intro: 'Lecco, tra lago e montagna: per chi vive tra la città e i paesi del lago, la videochiamata garantisce sedute senza spostamenti.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Livorno',
    slug: 'livorno',
    provincia: 'Livorno',
    regione: 'Toscana',
    intro: 'Livorno, città di mare e porto: la terapia online si adatta a orari intensi e turni di lavoro, con sedute sicure e riservate.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Livorno?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Lodi',
    slug: 'lodi',
    provincia: 'Lodi',
    regione: 'Lombardia',
    intro: 'Lodi, tra Milano e la Bassa: per chi fa il pendolare, la seduta online è il modo più semplice per mantenere la terapia senza rinunce.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Lodi per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Lodi o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
    {
    nome: 'Lucca',
    slug: 'lucca',
    provincia: 'Lucca',
    regione: 'Toscana',
    intro: 'Lucca, tra le sue mura e la campagna: il supporto psicologico online rispetta i tuoi tempi e ti evita lo spostamento.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Macerata',
    slug: 'macerata',
    provincia: 'Macerata',
    regione: 'Marche',
    intro: 'Macerata, tra colline e università: gli studenti e chi lavora lontano trovano nella videochiamata un supporto continuo e flessibile.',
    faqExtra: [
      ['Come scelgo il terapeuta a Macerata?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Macerata?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Mantova',
    slug: 'mantova',
    provincia: 'Mantova',
    regione: 'Lombardia',
    intro: 'Mantova, tra laghi e Gonzaga: la terapia online porta il benessere a casa tua, con orari che rispettano la tua giornata.',
    faqExtra: [
      ['Devo vivere a Mantova per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Mantova o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Massa',
    slug: 'massa',
    provincia: 'Massa-Carrara',
    regione: 'Toscana',
    intro: 'Massa, tra Apuane e mare: per chi vive in provincia, la seduta in videochiamata evita il viaggio e garantisce regolarità.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'Matera',
    slug: 'matera',
    provincia: 'Matera',
    regione: 'Basilicata',
    intro: 'Matera, capitale europea della cultura tra i Sassi: la psicologia online unisce qualità e discrezione, senza spostamenti.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Matera?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Messina',
    slug: 'messina',
    provincia: 'Messina',
    regione: 'Sicilia',
    intro: 'Messina, porta della Sicilia sullo Stretto: la terapia online supera distanze e traghetti, offrendo supporto a tutta la provincia.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
  {
    nome: 'Milano',
    slug: 'milano',
    provincia: 'Milano',
    regione: 'Lombardia',
    intro: 'A Milano i ritmi di lavoro e la pressione quotidiana lasciano poco spazio al benessere: con la terapia online non devi incastrare spostamenti o orari di uno studio, prenoti la seduta quando sei libero, anche la sera dopo il lavoro.',
    local: `<h3>La terapia online a Milano: flessibilità per ritmi intensi</h3><p>A Milano i prezzi in studio superano spesso i <strong>70-100 euro</strong> a seduta e i ritmi lavorativi lasciano pochi spazi. La terapia online a <strong>45 euro</strong> elimina il problema degli orari: basta un telefono e 50 minuti, dal divano di casa o dall'ufficio.</p><p>È la scelta ideale per chi fa il pendolare, per chi lavora in azienda con orari lunghi e per chi si è trasferito all'estero ma vuole parlare nella propria lingua con un professionista italiano.</p>`,
    faqExtra: [
      ['Posso prenotare la sera o nel weekend, dopo il lavoro a Milano?', 'Sì: su Adatto x Te trovi orari flessibili, con sedute anche la sera e nel weekend, pensate per chi vive a Milano e ha una giornata piena.'],
      ['Devo andare in uno studio a Milano per la prima seduta?', 'No: tutto avviene in videochiamata sicura, da casa o dall\'ufficio. Il servizio copre Milano e tutta la provincia, senza spostamenti.'],
    ],
  },
  {
    nome: 'Modena',
    slug: 'modena',
    provincia: 'Modena',
    regione: 'Emilia-Romagna',
    intro: 'A Modena, città del lavoro e dell\'industria, la pressione quotidiana e gli orari intensi lasciano poco spazio al benessere: con le sedute online ti prendi cura di te senza spostamenti, anche nella pausa pranzo.',
    faqExtra: [
      ['Posso prenotare nella pausa pranzo o dopo il lavoro?', 'Sì, gli orari sono flessibili: scegli lo slot che preferisci tra quelli disponibili, anche in orari serali.'],
      ['La terapia online è efficace come quella in presenza?', 'Sì: la psicoterapia online ha dimostrato la stessa efficacia di quella in presenza per la maggior parte dei disturbi, e ha il vantaggio di eliminare gli spostamenti.'],
    ],
  },
    {
    nome: 'Monza',
    slug: 'monza',
    provincia: 'Monza e Brianza',
    regione: 'Lombardia',
    intro: 'Monza, tra la villa reale e la Brianza: per chi lavora o studia tra Monza e Milano, la seduta online elimina gli spostamenti.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
  {
    nome: 'Napoli',
    slug: 'napoli',
    provincia: 'Napoli',
    regione: 'Campania',
    intro: 'A Napoli e in tutta la provincia, la terapia online ti permette di iniziare un percorso senza dipendere dagli orari di uno studio o dagli spostamenti: scegli tu quando e da dove collegarti.',
    local: `<h3>Perché la terapia online conviene a Napoli</h3><p>A Napoli una seduta in studio costa in media <strong>60-80 euro</strong>, senza contare il tempo e lo stress degli spostamenti: tangenziale, centro e traffico dell'ora di punta possono assorbire un'ora tra andata e ritorno. Con Adatto x Te la seduta costa <strong>45 euro</strong> e ti colleghi da casa, anche nella pausa pranzo o dopo il turno.</p><p>Il modello si adatta bene a chi lavora su turni (sanità, porto, commercio), agli studenti universitari e a chi vive nell'hinterland o in provincia: stessa qualità di uno studio in città, senza dipendere da orari e mezzi.</p>`,
    faqExtra: [
      ['È possibile parlare con uno psicologo online restando anonimi?', 'Sì: il catalogo è anonimo e il nome del terapeuta viene mostrato solo dopo la prenotazione, per garantire la massima riservatezza.'],
      ['Posso fare terapia di coppia online da Napoli?', 'Sì: la seduta di coppia costa 50€ e si svolge in videochiamata, comoda anche quando i partner vivono in città diverse.'],
    ],
  },
    {
    nome: 'Novara',
    slug: 'novara',
    provincia: 'Novara',
    regione: 'Piemonte',
    intro: 'Novara, crocevia tra Milano e Torino: la terapia online è perfetta per i pendolari: ti colleghi da dove sei.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Novara?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Nuoro',
    slug: 'nuoro',
    provincia: 'Nuoro',
    regione: 'Sardegna',
    intro: 'Nuoro, cuore della Barbagia: per chi vive nei paesi dell\'interno, la videochiamata porta il terapeuta ovunque, senza chilometri.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Nuoro per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Nuoro o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
    {
    nome: 'Oristano',
    slug: 'oristano',
    provincia: 'Oristano',
    regione: 'Sardegna',
    intro: 'Oristano, tra stagni e Campidano: il supporto psicologico online è accessibile a tutta la provincia, senza spostamenti.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
  {
    nome: 'Padova',
    slug: 'padova',
    provincia: 'Padova',
    regione: 'Veneto',
    intro: 'A Padova, città universitaria, l\'ansia da esame e la pressione degli studi sono tra le difficoltà più comuni: con Adatto x Te trovi supporto specializzato in videochiamata, senza lasciare la scrivania.',
    local: `<h3>Psicologo online a Padova: un aiuto per studenti e pendolari del Veneto</h3><p>Padova è una città universitaria con un grande afflusso di studenti e lavoratori che ogni giorno arrivano dalla provincia (Cittadella, Abano, Camposampiero, Piove di Sacco). La terapia in studio costa in media <strong>50-75 euro</strong>; online <strong>45 euro</strong>, senza dipendere da treni e spostamenti.</p><p>Un'opzione comoda per gli studenti fuori sede, per chi lavora nei servizi e per chi alterna periodi a Padova e periodi altrove, mantenendo la continuità del percorso.</p>`,
    faqExtra: [
      ['Sono uno studente fuori sede a Padova: posso accedere?', 'Sì, il servizio è online da tutta Italia: ti colleghi da Padova come da casa, con la stessa qualità di una seduta in studio.'],
      ['Esistono pacchetti per un percorso continuativo?', 'Sì, il pacchetto di 3 sedute prevede uno sconto del 15%: un percorso regolare costa meno delle singole sedute.'],
    ],
  },
  {
    nome: 'Palermo',
    slug: 'palermo',
    provincia: 'Palermo',
    regione: 'Sicilia',
    intro: 'A Palermo, come nel resto della Sicilia, la psicologia online elimina le barriere geografiche: bastano una connessione e un dispositivo per iniziare un percorso con professionisti qualificati.',
    local: `<h3>Psicologo online a Palermo: vicinanza senza dipendere dagli spostamenti</h3><p>Palermo è una città grande e i suoi quartieri sono spesso lontani tra loro: una seduta in studio costa in media <strong>50-70 euro</strong> e può richiedere un lungo tragitto a seconda della zona. Online la seduta costa <strong>45 euro</strong> e arriva dove sei tu, anche in provincia (Bagheria, Monreale, Carini, Partinico).</p><p>Un supporto prezioso per chi lavora nei servizi o nel commercio, per gli studenti e per chi si sente più a suo agio a parlare da casa, nel proprio spazio.</p>`,
    faqExtra: [
      ['Vivo in provincia di Palermo: posso accedere al servizio?', 'Sì, il servizio è completamente online e copre tutta la provincia e la regione: non serve recarsi in uno studio.'],
      ['Quali sono i prezzi a Palermo?', 'I prezzi sono nazionali e trasparenti: 45€ la seduta individuale, 50€ quella di coppia, pagamento sicuro online.'],
    ],
  },
  {
    nome: 'Parma',
    slug: 'parma',
    provincia: 'Parma',
    regione: 'Emilia-Romagna',
    intro: 'A Parma, tra lavoro e famiglia, ritagliare il tempo per la propria salute mentale è più semplice con la terapia online: prenoti la seduta quando sei libero e ti colleghi da casa o dall\'ufficio.',
    faqExtra: [
      ['Come funziona la videochiamata?', 'Ti colleghi al link della seduta direttamente dal browser, senza installare nulla: bastano un dispositivo e una connessione stabile.'],
      ['Quali specialisti sono disponibili?', 'Trovi psicologi per ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica.'],
    ],
  },
    {
    nome: 'Pavia',
    slug: 'pavia',
    provincia: 'Pavia',
    regione: 'Lombardia',
    intro: 'Pavia, tra la Certosa e l\'università: la seduta online è ideale per studenti e pendolari verso Milano.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
  {
    nome: 'Perugia',
    slug: 'perugia',
    provincia: 'Perugia',
    regione: 'Umbria',
    intro: 'A Perugia, con la sua grande comunità di studenti italiani e stranieri, la terapia online offre un supporto accessibile e flessibile: sedute in italiano, inglese, francese e spagnolo, quando ne hai bisogno.',
    faqExtra: [
      ['Sono uno studente internazionale a Perugia: ci sono sedute in inglese?', 'Sì, la consulenza multilingue è uno dei servizi di Adatto x Te: sedute anche in inglese, francese e spagnolo.'],
      ['Come prenoto una seduta?', 'Ti registri gratuitamente, scegli il terapeuta e l\'orario, paghi online in modo sicuro e ricevi il link per la videochiamata.'],
    ],
  },
    {
    nome: 'Pesaro',
    slug: 'pesaro',
    provincia: 'Pesaro-Urbino',
    regione: 'Marche',
    intro: 'Pesaro, città della musica tra mare e colline: il supporto psicologico online ti raggiunge ovunque, in tutta la provincia.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
  {
    nome: 'Pescara',
    slug: 'pescara',
    provincia: 'Pescara',
    regione: 'Abruzzo',
    intro: 'A Pescara e in tutto l\'Abruzzo, la terapia online supera le distanze della regione: una seduta di 50 minuti in videochiamata, da casa, in ufficio o ovunque tu sia.',
    faqExtra: [
      ['Vivo in provincia di Pescara: devo raggiungere la città?', 'No: il servizio è completamente online e funziona ovunque, ti serve solo una connessione stabile.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, con sconto del 15% sul pacchetto di 3 sedute. Paghi online con PayPal o carta.'],
    ],
  },
    {
    nome: 'Piacenza',
    slug: 'piacenza',
    provincia: 'Piacenza',
    regione: 'Emilia-Romagna',
    intro: 'Piacenza, tra Emilia e Lombardia: per chi vive tra due regioni, la videochiamata garantisce continuità senza spostamenti.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Pisa',
    slug: 'pisa',
    provincia: 'Pisa',
    regione: 'Toscana',
    intro: 'Pisa, tra la torre e l\'università: studenti e lavoratori trovano nella terapia online un supporto flessibile e continuo.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Pisa?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
    {
    nome: 'Pistoia',
    slug: 'pistoia',
    provincia: 'Pistoia',
    regione: 'Toscana',
    intro: 'Pistoia, tra il vivaismo e l\'Appennino: la psicologia online è comoda, discreta e accessibile a tutta la provincia.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Pistoia per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Pistoia o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
    {
    nome: 'Pordenone',
    slug: 'pordenone',
    provincia: 'Pordenone',
    regione: 'Friuli-Venezia Giulia',
    intro: 'Pordenone, città dell\'industria e del Noncello: la seduta online si adatta a turni e impegni, senza spostarti.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Potenza',
    slug: 'potenza',
    provincia: 'Potenza',
    regione: 'Basilicata',
    intro: 'Potenza, il capoluogo più alto d\'Italia: la terapia online supera le distanze della Basilicata e offre continuità.',
    faqExtra: [
      ['Come scelgo il terapeuta a Potenza?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Potenza?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Prato',
    slug: 'prato',
    provincia: 'Prato',
    regione: 'Toscana',
    intro: 'Prato, città del tessile: per chi lavora tra capannoni e distretti, la videochiamata porta il terapeuta dove sei.',
    faqExtra: [
      ['Devo vivere a Prato per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Prato o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Ragusa',
    slug: 'ragusa',
    provincia: 'Ragusa',
    regione: 'Sicilia',
    intro: 'Ragusa, tra barocco e Iblei: la terapia online unisce qualità e comodità, senza gli spostamenti del sud-est siciliano.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'Ravenna',
    slug: 'ravenna',
    provincia: 'Ravenna',
    regione: 'Emilia-Romagna',
    intro: 'Ravenna, città dei mosaici e del porto: la seduta online si adatta ai tuoi ritmi, con terapeuti qualificati.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Ravenna?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
  {
    nome: 'Reggio Calabria',
    slug: 'reggio-calabria',
    provincia: 'Reggio Calabria',
    regione: 'Calabria',
    intro: 'A Reggio Calabria e nella provincia, la terapia online elimina le barriere geografiche e di collegamento: inizi un percorso con professionisti qualificati senza spostarti, anche dalle zone più periferiche.',
    faqExtra: [
      ['Il servizio è disponibile in tutta la provincia?', 'Sì, il servizio è online da tutta Italia: funziona ovunque ci sia una connessione stabile, senza necessità di spostamenti.'],
      ['Come scelgo lo specialista?', 'Confronti i profili verificati dei terapeuti per specializzazione e recensioni e prenoti in autonomia l\'orario che preferisci.'],
    ],
  },
    {
    nome: 'Reggio Emilia',
    slug: 'reggio-emilia',
    provincia: 'Reggio Emilia',
    regione: 'Emilia-Romagna',
    intro: 'Reggio Emilia, tra il Tricolore e le ceramiche: la terapia online è comoda e flessibile, anche per chi viaggia per lavoro.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
    {
    nome: 'Rieti',
    slug: 'rieti',
    provincia: 'Rieti',
    regione: 'Lazio',
    intro: 'Rieti, tra le montagne laziali: per chi vive in provincia, la seduta online evita il viaggio a Roma.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
    {
    nome: 'Rimini',
    slug: 'rimini',
    provincia: 'Rimini',
    regione: 'Emilia-Romagna',
    intro: 'Rimini, tra mare e turismo: per chi lavora nel settore stagionale, la terapia online garantisce continuità tutto l\'anno.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Rimini?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
  {
    nome: 'Roma',
    slug: 'roma',
    provincia: 'Roma',
    regione: 'Lazio',
    intro: 'A Roma lo stress da traffico, i tempi lunghi degli spostamenti e la pressione di studio e concorsi pubblici mettono a dura prova: con Adatto x Te la seduta è in videochiamata, senza code né attese, ovunque tu sia nella capitale.',
    local: `<h3>Psicologo online a Roma: niente più spostamenti in una città enorme</h3><p>Roma è una delle città più estese d'Italia: raggiungere uno studio può significare attraversare mezza città tra traffico e parcheggi. Le sedute online a <strong>45 euro</strong> (contro i 60-90 euro in studio) si svolgono in videochiamata, da casa o dall'ufficio, senza stress.</p><p>Una scelta particolarmente utile per chi lavora nel settore pubblico o privato con orari rigidi, per i genitori con bambini piccoli e per chi vive nei Comuni limitrofi o nella provincia di Roma.</p>`,
    faqExtra: [
      ['Preparo un concorso pubblico a Roma: mi potete aiutare?', 'Sì: su Adatto x Te trovi psicologi specializzati in preparazione ai concorsi, con supporto per ansia da prestazione e gestione dello stress.'],
      ['Le sedute online a Roma funzionano bene?', 'Sì: la terapia online ha la stessa efficacia di quella in presenza ed eviti i tempi di spostamento nella città. Ti colleghi da dove preferisci.'],
    ],
  },
    {
    nome: 'Rovigo',
    slug: 'rovigo',
    provincia: 'Rovigo',
    regione: 'Veneto',
    intro: 'Rovigo, tra Po e Polesine: la psicologia online porta il benessere ovunque, anche nei piccoli comuni della provincia.',
    faqExtra: [
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
      ['Devo vivere a Rovigo per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Rovigo o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
    ],
  },
  {
    nome: 'Salerno',
    slug: 'salerno',
    provincia: 'Salerno',
    regione: 'Campania',
    intro: 'A Salerno e nella provincia, tra gli spostamenti verso Napoli e i ritmi quotidiani, la terapia online ti permette di ricevere supporto psicologico senza rinunce: prenoti e ti colleghi quando vuoi.',
    faqExtra: [
      ['Faccio il pendolare verso Napoli: posso prenotare in trasferta?', 'Sì, il servizio è online e ti colleghi da dove sei: a Salerno, in treno verso Napoli o a casa, con una connessione stabile.'],
      ['Quali sono i costi?', 'Prezzi trasparenti: 45€ la seduta individuale, 50€ di coppia, sconto 15% sul pacchetto di 3 sedute.'],
    ],
  },
    {
    nome: 'Sassari',
    slug: 'sassari',
    provincia: 'Sassari',
    regione: 'Sardegna',
    intro: 'Sassari, tra il Nord Sardegna e le sue borgate: la seduta online elimina gli spostamenti e rende la terapia accessibile.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Savona',
    slug: 'savona',
    provincia: 'Savona',
    regione: 'Liguria',
    intro: 'Savona, tra porto e Riviera: la terapia online si adatta a turni di lavoro e orari intensi.',
    faqExtra: [
      ['Come scelgo il terapeuta a Savona?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Savona?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Siena',
    slug: 'siena',
    provincia: 'Siena',
    regione: 'Toscana',
    intro: 'Siena, tra il Palio e le Crete: il supporto psicologico online rispetta la tua privacy, da casa tua.',
    faqExtra: [
      ['Devo vivere a Siena per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Siena o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Siracusa',
    slug: 'siracusa',
    provincia: 'Siracusa',
    regione: 'Sicilia',
    intro: 'Siracusa, tra Ortigia e il barocco: la videochiamata porta il terapeuta a casa tua, in tutta la provincia aretusea.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
    {
    nome: 'Sondrio',
    slug: 'sondrio',
    provincia: 'Sondrio',
    regione: 'Lombardia',
    intro: 'Sondrio, nelle valli alpine: per chi vive in montagna, la terapia online evita il viaggio in pianura e garantisce continuità.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Sondrio?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Taranto',
    slug: 'taranto',
    provincia: 'Taranto',
    regione: 'Puglia',
    intro: 'Taranto, città dei due mari: la terapia online offre un supporto discreto e flessibile, per tutta la provincia.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
    {
    nome: 'Teramo',
    slug: 'teramo',
    provincia: 'Teramo',
    regione: 'Abruzzo',
    intro: 'Teramo, tra Gran Sasso e colline: per chi vive nei comuni della provincia, la seduta online evita il viaggio e garantisce continuità.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
    {
    nome: 'Terni',
    slug: 'terni',
    provincia: 'Terni',
    regione: 'Umbria',
    intro: 'Terni, città dell\'acciaio: tra lavoro e Cascata delle Marmore, la seduta online si inserisce nei tuoi ritmi.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
  {
    nome: 'Torino',
    slug: 'torino',
    provincia: 'Torino',
    regione: 'Piemonte',
    intro: 'A Torino, tra lavoro e famiglia, trovare il tempo per prendersi cura di sé non è semplice: le sedute online di Adatto x Te si adattano ai tuoi orari, senza spostamenti per la città.',
    local: `<h3>Psicologo online a Torino: tempi e costi sotto controllo</h3><p>Nella città dell'industria e dei grandi insediamenti aziendali gli orari di lavoro contano più che altrove: una seduta in studio a Torino costa in media <strong>55-80 euro</strong> e richiede di attraversare la città dopo il lavoro. Online la seduta costa <strong>45 euro</strong> e si fa dal divano, anche durante la pausa.</p><p>Particolarmente utile per chi lavora in fabbrica o in ufficio con turni, per gli studenti delle università torinesi e per chi vive nei comuni dell'hinterland come Settimo, Moncalieri o Rivoli.</p>`,
    faqExtra: [
      ['Quanto costa una seduta di psicologia online a Torino?', 'La seduta individuale costa 45€, quella di coppia 50€, con sconto del 15% sul pacchetto di 3 sedute. Paghi online in modo sicuro.'],
      ['Come funziona la videochiamata?', 'Ti colleghi al link della seduta direttamente dal browser, con Jitsi: nessuna installazione, bastano un dispositivo e una connessione stabile.'],
    ],
  },
    {
    nome: 'Trani',
    slug: 'trani',
    provincia: 'Barletta-Andria-Trani',
    regione: 'Puglia',
    intro: 'Trani, la perla dell\'Adriatico tra la BAT: la terapia online rende il supporto psicologico comodo e discreto, senza spostamenti.',
    faqExtra: [
      ['Devo vivere a Trani per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Trani o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Trapani',
    slug: 'trapani',
    provincia: 'Trapani',
    regione: 'Sicilia',
    intro: 'Trapani, tra sale e mare: la psicologia online è accessibile a tutta la provincia, senza spostamenti.',
    faqExtra: [
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
    ],
  },
  {
    nome: 'Trento',
    slug: 'trento',
    provincia: 'Trento',
    regione: 'Trentino-Alto Adige',
    intro: 'A Trento e nelle valli del Trentino, dove le distanze tra i paesi rendono difficili gli spostamenti, la terapia online porta il supporto psicologico ovunque: bastano una connessione e un dispositivo.',
    faqExtra: [
      ['Vivo in una valle del Trentino: posso accedere?', 'Certo, il servizio è completamente online e funziona ovunque: non serve recarsi in città per una seduta.'],
      ['Come pago la seduta?', 'Pagamento online sicuro con PayPal o carta: 45€ individuale, 50€ di coppia, sconto 15% sul pacchetto di 3 sedute.'],
    ],
  },
    {
    nome: 'Treviso',
    slug: 'treviso',
    provincia: 'Treviso',
    regione: 'Veneto',
    intro: 'Treviso, tra i portici e la campagna veneta: la terapia online è comoda, riservata e flessibile.',
    faqExtra: [
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
      ['Come scelgo il terapeuta a Treviso?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
    ],
  },
  {
    nome: 'Trieste',
    slug: 'trieste',
    provincia: 'Trieste',
    regione: 'Friuli-Venezia Giulia',
    intro: 'A Trieste, città di confine e crocevia di culture, la terapia online offre flessibilità e riservatezza: sedute in videochiamata anche in inglese, francese e spagnolo, per una città internazionale.',
    faqExtra: [
      ['Ci sono sedute in altre lingue a Trieste?', 'Sì, Adatto x Te offre consulenza multilingue: sedute anche in inglese, francese e spagnolo.'],
      ['Come funziona la prenotazione?', 'Ti registri, scegli il terapeuta e l\'orario, paghi online e ricevi il link per la videochiamata sicura.'],
    ],
  },
    {
    nome: 'Udine',
    slug: 'udine',
    provincia: 'Udine',
    regione: 'Friuli-Venezia Giulia',
    intro: 'Udine, tra le colline e la pianura friulana: il supporto psicologico online ti raggiunge ovunque, in tutta la provincia.',
    faqExtra: [
      ['Posso scrivere al terapeuta tra le sedute?', 'Sì: i messaggi con il terapeuta sono illimitati, per restare in contatto tra una seduta e l\'altra.'],
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
    ],
  },
    {
    nome: 'Urbino',
    slug: 'urbino',
    provincia: 'Pesaro-Urbino',
    regione: 'Marche',
    intro: 'Urbino, città ducale tra le colline marchigiane: la videochiamata porta il supporto psicologico anche nei comuni più piccoli della provincia.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quali percorsi sono disponibili a Urbino?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
    {
    nome: 'Varese',
    slug: 'varese',
    provincia: 'Varese',
    regione: 'Lombardia',
    intro: 'Varese, tra i laghi e le Prealpi: per chi vive tra città e collina, la videochiamata garantisce sedute senza spostamenti.',
    faqExtra: [
      ['Come scelgo il terapeuta a Varese?', 'Il catalogo è anonimo per tutelare la privacy: scegli per specializzazione e, dopo la prenotazione, conosci il professionista.'],
      ['Quali percorsi sono disponibili a Varese?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
    ],
  },
  {
    nome: 'Venezia',
    slug: 'venezia',
    provincia: 'Venezia',
    regione: 'Veneto',
    intro: 'A Venezia e nella terraferma, raggiungere uno studio richiede spesso tragitti lunghi e costosi: con Adatto x Te la seduta è in videochiamata, anche solo per 50 minuti, da casa o dall\'ufficio.',
    faqExtra: [
      ['Posso fare terapia online vivendo in un\'isola o nella terraferma di Venezia?', 'Sì, il servizio è online e funziona ovunque: ti serve solo una connessione stabile, senza spostamenti in vaporetto o in auto.'],
      ['Come pago la seduta?', 'Il pagamento è online e sicuro con PayPal o carta: 45€ individuale, 50€ di coppia, sconto 15% sul pacchetto di 3 sedute.'],
    ],
  },
    {
    nome: 'Verbania',
    slug: 'verbania',
    provincia: 'Verbano-Cusio-Ossola',
    regione: 'Piemonte',
    intro: 'Verbania, sul Lago Maggiore: la terapia online porta il benessere anche nei comuni più belli e remoti della provincia.',
    faqExtra: [
      ['Devo vivere a Verbania per prenotare?', 'No: il servizio è online da tutta Italia. Se vivi a Verbania o in provincia, scegli giorno e ora e ti colleghi in videochiamata sicura.'],
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
    ],
  },
    {
    nome: 'Vercelli',
    slug: 'vercelli',
    provincia: 'Vercelli',
    regione: 'Piemonte',
    intro: 'Vercelli, tra risaie e pianura: la seduta online è la soluzione comoda per chi lavora in campagna o in città.',
    faqExtra: [
      ['Come funziona la prima seduta?', 'La prima seduta individuale è gratuita (15 minuti conoscitivi): conosci il terapeuta e capisci se fa per te, senza pagare.'],
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
    ],
  },
  {
    nome: 'Verona',
    slug: 'verona',
    provincia: 'Verona',
    regione: 'Veneto',
    intro: 'A Verona e nella sua provincia, tra lavoro, famiglia e i ritmi di una città turistica, la terapia online si adatta ai tuoi orari: 50 minuti in videochiamata, quando e dove preferisci.',
    local: `<h3>La terapia online per chi vive a Verona e provincia</h3><p>Verona ha un tessuto di piccole e medie imprese e una vita fatta di spostamenti tra la città e la provincia: tra lavoro e famiglia trovare un'ora libera per uno studio in centro non è semplice. La seduta online a <strong>45 euro</strong> (contro i 50-75 euro in studio) si inserisce nei ritagli della giornata.</p><p>Una soluzione apprezzata anche da chi lavora nel settore turistico e alberghiero, con orari variabili, e da chi vive nei comuni del lago o della Valpolicella.</p>`,
    faqExtra: [
      ['Vivo in provincia di Verona: devo spostarmi in città?', 'No, il servizio è online e funziona ovunque: ti colleghi da casa, dall\'ufficio o ovunque tu sia.'],
      ['Posso cancellare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto, senza complicazioni.'],
    ],
  },
    {
    nome: 'Vibo Valentia',
    slug: 'vibo-valentia',
    provincia: 'Vibo Valentia',
    regione: 'Calabria',
    intro: 'Vibo Valentia, tra mare e monti: la videochiamata porta il supporto psicologico a tutta la provincia vibonese.',
    faqExtra: [
      ['Quali percorsi sono disponibili a Vibo Valentia?', 'Ansia e depressione, terapia di coppia, psicologia dello sport, preparazione ai concorsi e psicologia giuridica: scegli la specializzazione più adatta.'],
      ['La terapia online è efficace quanto quella in presenza?', 'Sì: gli studi mostrano efficacia paragonabile per ansia, depressione e molti altri disturbi, con il vantaggio di non spostarti.'],
    ],
  },
    {
    nome: 'Vicenza',
    slug: 'vicenza',
    provincia: 'Vicenza',
    regione: 'Veneto',
    intro: 'Vicenza, città del Palladio: la terapia online si adatta a ritmi intensi, con sedute anche di sera e nel weekend.',
    faqExtra: [
      ['Che orari ci sono?', 'Prenoti direttamente online tra gli slot disponibili, anche di sera e nel weekend: niente attese in sala d\'attesa.'],
      ['Posso annullare o spostare una seduta?', 'Sì, dall\'area personale puoi cancellare o spostare una prenotazione prima dell\'orario previsto.'],
    ],
  },
    {
    nome: 'Viterbo',
    slug: 'viterbo',
    provincia: 'Viterbo',
    regione: 'Lazio',
    intro: 'Viterbo, tra la Tuscia e le terme: il supporto psicologico online è discreto e accessibile a tutta la provincia.',
    faqExtra: [
      ['Quanto costa una seduta?', '45€ la seduta individuale, 50€ quella di coppia, pacchetto 3 sedute con il 15% di sconto. Prima seduta conoscitiva gratuita.'],
      ['I dati sanitari sono protetti?', 'Sì: trattamento conforme al GDPR (art. 9 dati sanitari), videochiamate sicure e nessuna condivisione senza consenso.'],
    ],
  },
];
