// Paesi con comunità italiana significativa o grande presenza di expat italiani.
// Ogni voce alimenta una landing unica per paese e una per capitale.
// Struttura: { slug, nome, bandiera, capitale: { slug, nome, nota }, regione, fuso, comunita }
export const paesi = [
  { slug: 'stati-uniti', nome: 'Stati Uniti', bandiera: '🇺🇸', capitale: { slug: 'washington', nome: 'Washington', nota: 'capitale federale e città dove lavorano molti professionisti italiani' }, regione: 'Nord America', fuso: 'da -5 a -8 ore rispetto all\'Italia', comunita: 'una delle comunità italiane più grandi al mondo, da New York alla California' },
  { slug: 'canada', nome: 'Canada', bandiera: '🇨🇦', capitale: { slug: 'ottawa', nome: 'Ottawa', nota: 'capitale amministrativa con una comunità italiana attiva' }, regione: 'Nord America', fuso: 'da -4 a -9 ore rispetto all\'Italia', comunita: 'comunità storica e organizzata, con forti presenze a Montréal e Toronto' },
  { slug: 'regno-unito', nome: 'Regno Unito', bandiera: '🇬🇧', capitale: { slug: 'londra', nome: 'Londra', nota: 'prima destinazione europea dei giovani italiani' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'una delle comunità italiane più numerose e giovani d\'Europa' },
  { slug: 'germania', nome: 'Germania', bandiera: '🇩🇪', capitale: { slug: 'berlino', nome: 'Berlino', nota: 'capitale creativa con molti italiani giovani e professionisti' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'una delle comunità italiane più numerose d\'Europa' },
  { slug: 'svizzera', nome: 'Svizzera', bandiera: '🇨🇭', capitale: { slug: 'berna', nome: 'Berna', nota: 'capitale federale, hub di aziende e istituzioni' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'migliaia di italiani tra frontalieri e residenti' },
  { slug: 'belgio', nome: 'Belgio', bandiera: '🇧🇪', capitale: { slug: 'bruxelles', nome: 'Bruxelles', nota: 'capitale europea, sede delle istituzioni UE con molti italiani' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'comunità storica rafforzata dalla presenza delle istituzioni europee' },
  { slug: 'spagna', nome: 'Spagna', bandiera: '🇪🇸', capitale: { slug: 'madrid', nome: 'Madrid', nota: 'capitale con una comunità italiana in forte crescita' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'comunità in forte crescita, soprattutto tra i giovani' },
  { slug: 'paesi-bassi', nome: 'Paesi Bassi', bandiera: '🇳🇱', capitale: { slug: 'amsterdam', nome: 'Amsterdam', nota: 'capitale dinamica con molti italiani nel tech e nel design' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'comunità giovane e in crescita, legata a lavoro e studio' },
  { slug: 'irlanda', nome: 'Irlanda', bandiera: '🇮🇪', capitale: { slug: 'dublino', nome: 'Dublino', nota: 'hub tecnologico europeo con una grande presenza italiana' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'comunità giovane legata all\'hub tech di Dublino' },
  { slug: 'austria', nome: 'Austria', bandiera: '🇦🇹', capitale: { slug: 'vienna', nome: 'Vienna', nota: 'capitale con stretti legami storici con l\'Italia' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'stretti legami storici e culturali con l\'Italia' },
  { slug: 'lussemburgo', nome: 'Lussemburgo', bandiera: '🇱🇺', capitale: { slug: 'lussemburgo', nome: 'Lussemburgo', nota: 'la capitale con la più alta concentrazione di italiani pro capite' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'altissima concentrazione di italiani, tra finanza e istituzioni europee' },
  { slug: 'portogallo', nome: 'Portogallo', bandiera: '🇵🇹', capitale: { slug: 'lisbona', nome: 'Lisbona', nota: 'capitale che attrae sempre più italiani e digital nomad' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'comunità in crescita, anche tra i nomadi digitali' },
  { slug: 'australia', nome: 'Australia', bandiera: '🇦🇺', capitale: { slug: 'canberra', nome: 'Canberra', nota: 'capitale amministrativa con comunità italiana presente' }, regione: 'Oceania', fuso: 'da +8 a +10 ore rispetto all\'Italia', comunita: 'comunità storica e organizzata, con forti presenze a Melbourne e Sydney' },
  { slug: 'argentina', nome: 'Argentina', bandiera: '🇦🇷', capitale: { slug: 'buenos-aires', nome: 'Buenos Aires', nota: 'capitale con una delle più grandi discendenze italiane' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'fortissima discendenza italiana, legami culturali profondi' },
  { slug: 'brasile', nome: 'Brasile', bandiera: '🇧🇷', capitale: { slug: 'brasilia', nome: 'Brasilia', nota: 'capitale moderna con comunità italiana presente' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'la più grande discendenza italiana fuori dall\'Italia' },
  { slug: 'uruguay', nome: 'Uruguay', bandiera: '🇺🇾', capitale: { slug: 'montevideo', nome: 'Montevideo', nota: 'capitale con una fortissima componente di origine italiana' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'una delle discendenze italiane più alte al mondo' },
  { slug: 'venezuela', nome: 'Venezuela', bandiera: '🇻🇪', capitale: { slug: 'caracas', nome: 'Caracas', nota: 'capitale con una comunità italiana storica' }, regione: 'Sud America', fuso: 'da -5 a -6 ore rispetto all\'Italia', comunita: 'comunità italiana storica e radicata' },
  { slug: 'cile', nome: 'Cile', bandiera: '🇨🇱', capitale: { slug: 'santiago', nome: 'Santiago', nota: 'capitale con una comunità italiana consolidata' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'comunità consolidata con legami culturali forti' },
  { slug: 'messico', nome: 'Messico', bandiera: '🇲🇽', capitale: { slug: 'citta-del-messico', nome: 'Città del Messico', nota: 'capitale con una comunità italiana in crescita' }, regione: 'Nord America', fuso: 'da -7 a -8 ore rispetto all\'Italia', comunita: 'comunità in crescita tra aziende e istituzioni' },
  { slug: 'emirati-arabi', nome: 'Emirati Arabi', bandiera: '🇦🇪', capitale: { slug: 'abu-dhabi', nome: 'Abu Dhabi', nota: 'capitale con molti professionisti italiani in azienda' }, regione: 'Medio Oriente', fuso: '+2 ore rispetto all\'Italia', comunita: 'molti professionisti italiani tra finanza, energia e costruzioni' },
  { slug: 'singapore', nome: 'Singapore', bandiera: '🇸🇬', capitale: { slug: 'singapore', nome: 'Singapore', nota: 'città-stato, hub finanziario asiatico con italiani in carriera' }, regione: 'Asia', fuso: '+6 ore rispetto all\'Italia', comunita: 'comunità di professionisti in finanza e tech' },
  { slug: 'cina', nome: 'Cina', bandiera: '🇨🇳', capitale: { slug: 'pechino', nome: 'Pechino', nota: 'capitale con una presenza italiana tra istituzioni e imprese' }, regione: 'Asia', fuso: '+7 ore rispetto all\'Italia', comunita: 'presenza italiana tra Pechino e Shanghai, soprattutto per lavoro' },
  { slug: 'giappone', nome: 'Giappone', bandiera: '🇯🇵', capitale: { slug: 'tokyo', nome: 'Tokyo', nota: 'capitale con una piccola ma attiva comunità italiana' }, regione: 'Asia', fuso: '+8 ore rispetto all\'Italia', comunita: 'comunità piccola ma attiva, tra moda, design e aziende' },
  { slug: 'sudafrica', nome: 'Sudafrica', bandiera: '🇿🇦', capitale: { slug: 'pretoria', nome: 'Pretoria', nota: 'capitale amministrativa con comunità italiana storica' }, regione: 'Africa', fuso: 'da 0 a +1 ora rispetto all\'Italia', comunita: 'comunità storica, con presenze a Johannesburg e Città del Capo' },
];
