// paesi-zone.js — blocco `zoneNota` per le pagine /italiani-all-estero/<paese>.
//
// PERCHE' SOLO QUESTO: le guide esistenti (4.750 caratteri di media, 5-9 sezioni)
// coprono gia' lingua, fuso orario, nostalgia, comunita', clima e stagionalita'.
// L'unica cosa assente su tutti i 180.495 caratteri era il rimborso delle sedute:
// zero occorrenze di assicurazione, cassa malattia, NHS, Krankenkasse, mutuelle.
// Aggiungere altro avrebbe duplicato il testo esistente.
//
// REGOLA: si indica il sistema locale e cosa chiedere, mai cifre o percentuali.
// Le regole cambiano e non le ho verificate una per una: un numero sbagliato su un
// sito di salute e' peggio di nessun numero.
//
// Il merge in paesi.js e' per campo, quindi basta questo file.

export const paesiZone = [
  {
    slug: 'stati-uniti',
    zoneNota: "<h2>Chi paga le sedute negli Stati Uniti</h2><p>Negli Stati Uniti non esiste una copertura sanitaria unica: la terapia passa quasi sempre dal piano assicurativo legato al datore di lavoro. La legge federale che regola questo terreno si chiama <em>Mental Health Parity and Addiction Equity Act</em> e impedisce ai piani che offrono prestazioni di salute mentale di applicare limiti più restrittivi di quelli previsti per le cure mediche e chirurgiche. Non obbliga però un datore di lavoro a offrire la copertura.</p><p>Prima di cominciare conviene quindi chiedere al proprio piano tre cose: se la seduta è coperta, quanto resta a carico tuo e se il piano riconosce un professionista che non si trova negli Stati Uniti. È su quest'ultimo punto che cadono molte coperture. La descrizione ufficiale della norma è sul sito dei <em>Centers for Medicare and Medicaid Services</em> (cms.gov).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'canada',
    zoneNota: "<h2>Il rimborso passa dalla provincia, e poi dal datore di lavoro</h2><p>In Canada la sanità pubblica è provinciale, e la legge federale che ne fissa i confini, il <em>Canada Health Act</em>, definisce i servizi assicurati come i servizi ospedalieri e medici, lasciando fuori la psicoterapia ambulatoriale svolta con un professionista privato. Quello che nella pratica decide tutto è quindi il benefit aziendale: molti contratti prevedono un massimale annuo per la salute mentale, gestito da una compagnia assicurativa (laws-lois.justice.gc.ca).</p><p>La domanda utile da fare all'ufficio del personale è una sola: quel massimale vale anche per un professionista che lavora dall'estero? È la domanda che quasi nessuno fa e che cambia l'esito del percorso.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'regno-unito',
    zoneNota: "<h2>NHS e privato: cosa aspettarsi davvero</h2><p>Il percorso pubblico per ansia e depressione ha un nome proprio: <em>NHS Talking Therapies</em>. In Inghilterra si accede per auto-segnalazione, senza dover passare dal medico di base, ma resta la variabile che decide tutto: il tempo di attesa, che il servizio stesso comunica prima del primo appuntamento (nhs.uk).</p><p>Il NHS esiste, e per la salute mentale il percorso parte dal medico di base, che indirizza ai servizi di zona. Il problema sono i tempi, che si contano in mesi. Per questo molti finiscono per pagare un professionista privato di tasca propria. Se hai un'assicurazione privata, controlla due cose: se copre la salute mentale e se la copertura vale per sedute in videochiamata con un professionista all'estero.</p><p>Le sedute si tengono in italiano.</p>",
  },
  {
    slug: 'francia',
    zoneNota: "<h2>La Sécu, la mutuelle, e quello che resta fuori</h2><p>Dal 2022 esiste un dispositivo pubblico che vale la pena conoscere: <em>Mon soutien psy</em>. Dà diritto a <strong>fino a 12 sedute all'anno</strong> con uno psicologo convenzionato, su prescrizione del medico. La seduta costa <strong>50 €</strong> e viene rimborsata in parte dall'Assurance Maladie. È la via più economica, ma passa dalla prescrizione e dall'elenco dei professionisti convenzionati.</p><p>In Francia l'assicurazione sanitaria pubblica rimborsa il medico, ma lo psicologo liberale è rimasto a lungo escluso. Esistono dispositivi pubblici di sostegno, con un numero limitato di sedute e un elenco di professionisti convenzionati: se ne sente parlare, ma le condizioni cambiano e conviene informarsi aggiornati. Se hai una mutuelle aziendale, leggi la voce dedicata alla psicologia: molte coprono un pacchetto annuo di sedute, a volte anche a distanza.</p><p>Le regole del dispositivo e del rimborso sono pubblicate dall'Assurance Maladie sul sito ameli.fr. Le sedute si svolgono in italiano.</p>",
  },
  {
    slug: 'germania',
    zoneNota: "<h2>Le Krankenkassen e il percorso a tappe</h2><p>Un dettaglio che sorprende quasi tutti: la psicoterapia <strong>non è una prestazione standard</strong> delle casse malattia. Si ottiene solo presentando domanda, e nella procedura di rimborso serve un rapporto clinico scritto destinato a un perito. È la ragione per cui, anche avendo la copertura, trovare un posto di terapia può richiedere mesi.</p><p>In Germania la psicoterapia rientra nella copertura sanitaria, pubblica o privata. Il percorso però ha tappe obbligate: si parte dal medico di base per un primo colloquio orientativo, poi si cerca un terapeuta con un posto libero — e i posti sono pochi, con attese che in alcune città superano i sei mesi. Con un'assicurazione privata le regole sono diverse, spesso più rapide. Nessuno di questi percorsi si applica a un professionista che lavora dall'Italia: è una cosa da verificare prima, non dopo.</p><p>Il quadro delle prestazioni è descritto dal Ministero federale della Salute sul sito bundesgesundheitsministerium.de. Le sedute si svolgono in italiano.</p>",
  },
  {
    slug: 'spagna',
    zoneNota: "<h2>Seguridad Social: dove entra la psicoterapia</h2><p>In Spagna la salute mentale rientra nell'assistenza specialistica del Sistema Nacional de Salud. La <em>Cartera común de servicios</em> del Ministerio de Sanidad elenca cosa comprende: diagnosi e monitoraggio clinico dei disturbi mentali, psicofarmacoterapia, psicoterapie individuali, di gruppo o familiari, terapia elettroconvulsiva e, quando serve, il ricovero.</p><p>L'accesso non è diretto: si passa dal medico di atención primaria, che invia allo specialista, e i tempi variano molto da regione a regione. Nel privato esistono polizze con copertura psicologica e pacchetti di sedute incluse: è lì che conviene guardare, perché è l'unica strada che può riconoscere sedute fatte a distanza. Il dettaglio delle prestazioni è pubblicato su sanidad.gob.es.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'paesi-bassi',
    zoneNota: "<h2>Il medico di base decide se il rimborso parte</h2><p>Nei Paesi Bassi l'assicurazione sanitaria di base copre l'assistenza di salute mentale, ma il percorso parte sempre dal <em>huisarts</em>, il medico di base: è lui a gestire i disturbi lievi e a indirizzare verso la basis-ggz o la gespecialiseerde ggz. Senza la sua lettera di invio il rimborso non parte. Lo spiega la pagina del governo olandese dedicata all'assistenza psicologica (rijksoverheid.nl).</p><p>Su una cosa conviene essere preparati: sul basispakket grava un <em>eigen risico</em>, la franchigia obbligatoria che si paga di tasca propria, mentre le prestazioni del medico di base ne restano escluse. Molte persone arrivate per lavoro hanno anche un'assicurazione integrativa che copre un pacchetto di sedute, a volte anche all'estero: è la prima cosa da controllare.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'irlanda',
    zoneNota: "<h2>HSE, o il ricorso al privato</h2><p>In Irlanda la salute mentale pubblica è in mano alla <em>Health Service Executive</em>, che la eroga attraverso i servizi comunitari: l'équipe comprende di norma uno psichiatra consulente e infermieri, e in molte aree anche uno psicologo clinico e un assistente sociale. Si entra parlando con il proprio medico di famiglia, che in alcuni casi può indirizzare direttamente a uno psicologo clinico o a un consulente per le dipendenze.</p><p>Per chi ha più di 18 anni esiste anche un servizio di counselling gratuito, il National Counselling Service. Le attese nel pubblico possono però essere lunghe, e la conseguenza più comune tra gli stranieri è pagare privatamente. Molte aziende, soprattutto nel settore tecnologico, includono un programma di supporto psicologico tra i benefit: è il primo posto dove guardare. Il quadro è descritto su citizensinformation.ie.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'portogallo',
    zoneNota: "<h2>Il Servizio sanitario nazionale e i tempi di attesa</h2><p>In Portogallo la salute mentale è dentro il Serviço Nacional de Saúde: si accede dagli ospedali, nei servizi di psichiatria e salute mentale, e la prima consulta specialistica richiede l'invio del medico di famiglia, con la possibilità di scegliere l'unità dove esiste la specialità. I tempi massimi di risposta sono fissati e pubblicati dal SNS: per le prime consulte di specialità la Portaria n.º 153/2017 indica un tetto di quattro mesi (sns.gov.pt).</p><p>La copertura è però disomogenea sul territorio, e molti finiscono per rivolgersi al privato o per usare l'assicurazione offerta dall'azienda. Prima di iniziare conviene verificare se il proprio piano riconosce un professionista che non si trova in Portogallo: è il punto su cui cadono quasi tutte le coperture. Il riferimento pubblico per la salute mentale è il Programa Nacional para a Saúde Mental (saudemental.min-saude.pt).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'australia',
    zoneNota: "<h2>Medicare, il piano del medico di base, e la differenza</h2><p>Il meccanismo ha un nome: <em>Better Access</em>. Il medico di base prepara un <em>Mental health treatment plan</em>, che dà diritto a <strong>10 sedute individuali e 10 di gruppo per anno solare</strong> con rimborso Medicare. Attenzione: il rimborso copre una parte della tariffa, e la differenza resta a carico di chi la riceve.</p><p>In Australia il medico di base può preparare un piano di cura per la salute mentale, che dà diritto a un numero limitato di sedute l'anno con rimborso parziale di Medicare. Attenzione a quella parola: il rimborso copre una parte della tariffa, non tutta, e la differenza resta a carico tuo. Per questo molti hanno anche un'assicurazione privata che copre la quota restante. Nessuno di questi meccanismi vale per un professionista che lavora dall'estero, quindi va verificato prima.</p><p>Le regole del programma e i criteri di accesso sono pubblicati dal Department of Health australiano sul sito health.gov.au. Le sedute si svolgono in italiano.</p>",
  },
  {
    slug: 'nuova-zelanda',
    zoneNota: "<h2>Un paese dove il percorso parte dal medico di famiglia</h2><p>In Nuova Zelanda il servizio sanitario pubblico si chiama <em>Health New Zealand</em>, noto anche come Te Whatu Ora, ed è lì che si accede alla salute mentale: si prenota dal proprio medico di famiglia o da un operatore di fiducia, che indirizza e trasmette l'invio ai servizi di salute mentale. Per le urgenze esistono i team di valutazione della crisi; per il supporto immediato c'è una linea gratuita attiva 24 ore su 24, sette giorni su sette (healthnz.govt.nz).</p><p>Un dettaglio che cambia le cose: esistono percorsi gratuiti e ad accesso diretto senza invio per alcune fasce della popolazione, tra cui i giovani dai 12 ai 24 anni, ma i servizi pubblici sono riservati a chi ha i requisiti di eleggibilità. Chi non li ha può comunque ricevere le cure, pagando però tutti i costi. Per un percorso di psicoterapia ordinario, quindi, si finisce quasi sempre a pagare privatamente.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'argentina',
    zoneNota: "<h2>Obras sociales, prepagas e chi controlla</h2><p>In Argentina la copertura sanitaria passa dalle <em>obras sociales</em>, legate al rapporto di lavoro, oppure dalle <em>prepagas</em> private. La legge nazionale sulla salute mentale, la Ley 26.657, stabilisce che la cura va affidata a un'équipe interdisciplinare che include l'area di psicologia, e prevede che l'autorità di applicazione, insieme alla Superintendencia de Servicios de Salud, promuova l'adeguamento della copertura delle obras sociales a quei principi.</p><p>La Superintendencia è anche l'ente davanti al quale si può reclamare: le pratiche e i reclami si presentano anche a distanza, tramite il Centro de Atención Virtual, ed esiste una mediazione obbligatoria prima di arrivare al contenzioso. Conviene comunque chiedere alla propria copertura quali sedute riconosce e se accetta un professionista che lavora dall'estero (sssalud.gob.ar).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'brasile',
    zoneNota: "<h2>Plano de saúde: cosa l'ANS obbliga a coprire</h2><p>In Brasile il riferimento è l'<em>Agência Nacional de Saúde Suplementar</em>, che pubblica il Rol de Procedimentos: l'elenco delle prestazioni che i piani di salute sono obbligati a offrire, e che comprende le sedute e le consultazioni con lo psicologo. Vale per i contratti stipulati o adeguati dopo l'entrata in vigore dell'elenco.</p><p>Sul rimborso c'è una regola precisa: la richiesta si presenta alla propria operadora, che deve concludere l'analisi e pagare entro trenta giorni; il diritto esiste anche quando il contratto non lo prevede, se nella località cercata non c'è un professionista disponibile. È il punto su cui conviene informarsi per primi (gov.br/ans).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'cile',
    zoneNota: "<h2>Fonasa, Isapre e la garanzia GES</h2><p>In Cile la copertura sanitaria corre su due binari: il fondo pubblico <em>Fonasa</em> e le <em>Isapre</em>, le assicurazioni private. Per la depressione esiste una garanzia esplicita, il GES: per le persone dai 15 anni in su assicura l'accesso al trattamento con tempi massimi di attenzione definiti, e per i beneficiari Fonasa di qualunque fascia il copago previsto è azzerato.</p><p>Anche il reclamo ha una strada tracciata: se il centro di salute non eroga le prestazioni garantite o fa pagare chi non dovrebbe, si presenta un reclamo formale a Fonasa; se la risposta non arriva nei termini o non soddisfa, si può insistere davanti alla Superintendencia de Salud. Con le Isapre, invece, il rimborso delle sedute psicologiche è parziale e dipende dal piano (fonasa.gob.cl).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'cina',
    zoneNota: "<h2>Chi paga le sedute in Cina</h2><p>In Cina l'assicurazione sanitaria di base copre il trattamento dei disturbi mentali: per le persone assicurate, le spese ambulatoriali e di ricovero sostenute in strutture e farmacie convenzionate, per farmaci e prestazioni inclusi nel catalogo dell'assicurazione medica, sono rimborsate secondo le regole di policy. Il trattamento psichiatrico è definito in modo da includere la psicoterapia tra le modalità terapeutiche, e la <em>National Healthcare Security Administration</em> ha unificato a livello nazionale le voci di prezzo di questi trattamenti (nhsa.gov.cn).</p><p>Attenzione a un dettaglio: l'assicurazione di base è gestita provincia per provincia, e sono le singole province a fissare percentuali e massimali di rimborso. Chi ha un contratto internazionale si appoggia spesso a un'assicurazione privata o aziendale, che la psicoterapia la copre a volte e a volte no. Le sedute private si concentrano nelle cliniche internazionali di Pechino e Shanghai.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'corea-del-sud',
    zoneNota: "<h2>Il voucher nazionale per la consulenza psicologica</h2><p>In Corea del Sud esiste un programma pubblico dedicato: il Ministero della Salute e del Welfare gestisce un voucher per servizi professionali di consulenza psicologica, per un totale di otto sedute. I destinatari sono le persone con difficoltà emotive come depressione o ansia che rientrano in uno dei criteri previsti, tra cui un punteggio elevato in uno screening nazionale oppure una diagnosi o un parere di uno psichiatra.</p><p>Il meccanismo è semplice: il servizio ha un prezzo per seduta fissato dallo Stato, e l'utente paga una quota che dipende dalla fascia di reddito, mentre il resto lo copre la sovvenzione pubblica. La domanda si presenta di persona presso il centro di salute pubblica comunale o distrettuale, con la documentazione richiesta. Il riferimento è il Ministero della Salute e del Welfare (mohw.go.kr).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'croazia',
    zoneNota: "<h2>Liste d'attesa e privato: come si accede in Croazia</h2><p>In Croazia l'assicurazione sanitaria obbligatoria è gestita dall'<em>Hrvatski zavod za zdravstveno osiguranje</em>, l'istituto croato per l'assicurazione sanitaria. Le prestazioni specialistiche si ottengono, di regola, presso il fornitore convenzionato più vicino al proprio domicilio, e sempre sulla base di un'impegnativa rilasciata dal medico di medicina generale scelto (hzzo.hr).</p><p>È il meccanismo che decide anche i tempi: senza impegnativa il percorso non parte, e l'attesa dipende dal fornitore e dalla sua disponibilità. Per un percorso di psicoterapia conviene quindi verificare direttamente con l'istituto se e come la prestazione rientra nella copertura obbligatoria: una parte consistente delle sedute avviene comunque nel privato, a pagamento, con tariffe che variano sensibilmente tra Zagabria e le città più piccole.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'danimarca',
    zoneNota: "<h2>Chi paga le sedute in Danimarca</h2><p>In Danimarca il rimborso delle sedute dallo psicologo passa da una condizione precisa: serve un invio del proprio medico di base, da usare entro tre mesi. Il medico può emetterlo solo se il paziente rientra in una delle categorie previste, tra cui depressione e ansia di intensità lieve o moderata a partire da una certa età. Le regole della copertura pubblica sono descritte sul portale pubblico borger.dk.</p><p>Quando l'invio c'è, il rimborso copre una parte dell'onorario dello psicologo per un numero limitato di consultazioni, estendibile con un nuovo invio in alcuni casi. Il trattamento psichiatrico è invece gratuito, ma anche lì serve l'invio del medico. Fuori da questi percorsi si va nel privato, e un'assicurazione integrativa, molto diffusa nel paese, può coprire una parte della spesa.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'emirati-arabi',
    zoneNota: "<h2>L'assicurazione del datore di lavoro, e cosa copre davvero</h2><p>Negli Emirati la copertura sanitaria è obbligatoria e legata al contratto: ad Abu Dhabi il datore di lavoro o lo sponsor deve fornire l'assicurazione ai residenti non cittadini, e la fatturazione dei servizi segue la tariffa obbligatoria fissata dal <em>Department of Health</em>.</p><p>Sulla salute mentale però non esiste un pacchetto unico: il rimborso di valutazione, diagnosi e gestione dipende dallo schema di benefit e dal singolo piano assicurativo, ed è lo standard del dipartimento a fissare le regole per gli assicuratori autorizzati. In pratica significa una cosa sola: leggere la polizza prima di iniziare e chiedere se copre le sedute e se le riconosce anche a distanza (doh.gov.ae).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'finlandia',
    zoneNota: "<h2>Kela e la psicoterapia riabilitativa</h2><p>In Finlandia esiste un canale preciso per farsi rimborsare la psicoterapia, ed è gestito da <em>Kela</em>, l'istituto di previdenza sociale: si chiama kuntoutuspsykoterapia, la psicoterapia riabilitativa. Non è un accesso libero. Serve avere un'età tra i 16 e i 67 anni, avere un disturbo mentale che minaccia la capacità di lavoro o di studio, aver ricevuto un trattamento adeguato per almeno tre mesi, e avere il parere di uno psichiatra che ne attesti la necessità (kela.fi).</p><p>Solo dopo la decisione positiva di Kela la terapia può iniziare. Il rimborso, di norma, viene detratto direttamente dal terapeuta sul costo della seduta; se non è così, si chiede a Kela entro sei mesi dal pagamento. Chi non rientra nei criteri, o non vuole aspettare la decisione, trova nel privato la strada più rapida, pagando di tasca propria o con l'assicurazione del datore di lavoro.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'giappone',
    zoneNota: "<h2>Come si pagano le sedute in Giappone</h2><p>In Giappone la terapia psichiatrica ambulatoriale è una prestazione assicurata con un suo valore tariffario: la seduta è prevista con un punteggio più alto quando dura almeno mezz'ora e più basso sotto quella soglia, come si legge nella tabella ufficiale del Ministero della Salute, del Lavoro e del Welfare (mhlw.go.jp).</p><p>Esiste però un dispositivo che vale la pena conoscere: il sistema di sostegno per la cura psichiatrica ambulatoriale continua riduce la quota a carico del paziente dal 30 al 10 per cento, con un tetto mensile che dipende dal reddito del nucleo familiare. Il counselling svolto fuori da ospedali e cliniche resta invece escluso dalla copertura pubblica. Il sistema è sbilanciato verso la visita breve e la prescrizione più che verso la psicoterapia regolare: per questo molti percorsi continuativi finiscono nel privato, tra Tokyo e Osaka.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'grecia',
    zoneNota: "<h2>Copertura pubblica e privato: chi paga in Grecia</h2><p>In Grecia il riferimento è l'<em>EOPYY</em>, l'ente nazionale per l'erogazione dei servizi sanitari. Il regolamento unico delle prestazioni, all'articolo 42, prevede il rimborso delle psicoterapie, individuali, di gruppo o familiari, a favore degli assicurati che non siano già inseriti in un programma di salute mentale e che ne abbiano necessità; il numero di sedute è definito per tipo di psicoterapia e per diagnosi.</p><p>Due dettagli contano più del resto: il parere che apre il percorso può essere emesso solo da uno psichiatra, e le sedute vengono erogate senza compartecipazione del paziente. Poiché l'ente non ha stipulato convenzioni dedicate, il rimborso arriva direttamente all'assicurato, che presenta il parere medico, la ricevuta quietanzata e un'autocertificazione. La circolare che lo spiega è pubblicata su eopyy.gov.gr.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'india',
    zoneNota: "<h2>Chi paga le sedute in India</h2><p>In India la copertura della salute mentale è un obbligo di legge per le compagnie assicurative. L'<em>Insurance Regulatory and Development Authority of India</em>, l'autorità che regola il settore, ha ribadito che tutti i prodotti assicurativi devono coprire le malattie mentali e conformarsi alla legge sulla tutela della salute mentale del 2017, senza deroghe, e ha chiesto agli assicuratori di confermarne la conformità (irdai.gov.in).</p><p>Nella pratica paga quindi l'assicuratore, nei limiti della polizza sottoscritta: si stipula il contratto con una compagnia registrata e si presenta la richiesta di rimborso all'assicuratore, con la possibilità di ricorrere all'autorità in caso di rifiuto. Resta vero però che molta spesa ambulatoriale è ancora pagata di tasca propria, e che gli studi privati si concentrano a Mumbai, Delhi e Bangalore, con tariffe molto diverse da città a città.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'israele',
    zoneNota: "<h2>Le casse malattia e la riforma del 2015</h2><p>In Israele la salute mentale non passa più dal Ministero della Salute come un tempo: dal 1 luglio 2015, con la riforma dell'assicurazione per la salute mentale, la responsabilità dell'assistenza ambulatoriale è passata alle <em>kupot holim</em>, le casse malattia, cioè Clalit, Maccabi, Meuhedet e Leumit (gov.il).</p><p>In pratica la persona si rivolge alla propria cassa, che valuta e indirizza al percorso adeguato. Le casse finanziano la terapia negli ambulatori pubblici, dove il servizio è gratuito o comporta una piccola quota periodica; se invece il trattamento avviene fuori dalle strutture della cassa, serve un'autorizzazione preventiva. Esiste anche la via del terapeuta privato, parzialmente sovvenzionata, con una quota a carico dell'assicurato.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'malta',
    zoneNota: "<h2>Servizio pubblico e privato: dove si entra</h2><p>A Malta il servizio sanitario pubblico è gratuito e comprende la salute mentale. L'accesso non passa da un portale: chi sente il bisogno di parlare con qualcuno può rivolgersi direttamente a una delle Health Clinics per una valutazione e per la conseguente pianificazione della cura, oppure chiedere al proprio medico un invio a una Mental Health Clinic. Esiste anche una linea di supporto attiva a ogni ora (mentalhealthservices.gov.mt).</p><p>Per le situazioni acute c'è un team specialistico dedicato, il Crisis Resolution Home Treatment, che opera sette giorni su sette e segue la persona in clinica o al domicilio: si accede dopo una valutazione del servizio psichiatrico d'emergenza. Chi non vuole attendere le liste pubbliche si rivolge al privato, dove le tariffe sono più contenute che altrove in Europa e l'offerta si concentra tra La Valletta e Sliema.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'messico',
    zoneNota: "<h2>IMSS: come si entra nel percorso psicologico</h2><p>In Messico la copertura dei lavoratori dipendenti passa dall'<em>Instituto Mexicano del Seguro Social</em>, che mette a disposizione professionisti della psicologia nei tre livelli di assistenza per disturbi come depressione e ansia. Il percorso non è libero: la persona iscritta si reca nella propria Unidad de Medicina Familiar e il medico curante stabilisce se esiste la necessità di un invio al servizio, che può essere erogato nella stessa unità o nell'ospedale di zona di riferimento.</p><p>Questo primo passaggio è indicato come gratuito. Chi non è nel sistema formale, o vuole tempi rapidi, si rivolge al privato, dove le sedute si pagano di tasca e le assicurazioni di spesa medica raramente coprono la psicoterapia ambulatoriale. Il riferimento è imss.gob.mx.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'norvegia',
    zoneNota: "<h2>Rimborso pubblico e attese: la Norvegia</h2><p>In Norvegia si può ottenere il rimborso di una parte delle spese per il trattamento presso uno psicologo specialista in psicologia clinica, ma solo alle condizioni previste: serve un invio da un medico, da uno psicologo o dal servizio di protezione dell'infanzia, e lo psicologo deve avere un accordo di regolamento diretto con <em>Helfo</em>, l'ente che gestisce i rimborsi, e un accordo con un'azienda sanitaria regionale. Senza quell'accordo si paga tutto di tasca propria (helsenorge.no).</p><p>Anche senza invio si possono ottenere alcune sedute di valutazione. Il sistema funziona per quote: la parte a carico del paziente viene registrata e concorre a far scattare il <em>frikort</em>, la carta che esonera dal pagamento una volta superata una soglia di spesa annuale. Le attese restano però il vero ostacolo, e per molti percorsi si parla di mesi.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'polonia',
    zoneNota: "<h2>Chi paga le sedute in Polonia</h2><p>In Polonia il pagatore pubblico è il <em>Narodowy Fundusz Zdrowia</em>, il Fondo nazionale della salute, che finanzia le prestazioni garantite con i contributi di malattia. Le sedute di psicoterapia rientrano nell'area dell'assistenza psichiatrica: nel percorso dedicato ai minori, il primo livello di cura — il centro di assistenza psicologica e psicoterapeutica di comunità — eroga consulenza psicologica e sedute di psicoterapia individuale, familiare e di gruppo, e per accedervi l'impegnativa non è richiesta.</p><p>Per gli adulti vale la regola generale dell'assistenza specialistica ambulatoriale: serve l'impegnativa del medico di base o di un altro medico convenzionato, con una sola eccezione rilevante, lo psichiatra, per il quale l'impegnativa non serve. I tempi di attesa sono pubblicati nell'informator ufficiale del Fondo (nfz.gov.pl).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'repubblica-ceca',
    zoneNota: "<h2>Assicurazione obbligatoria e fondo prevenzione</h2><p>In Repubblica Ceca l'assicurazione sanitaria pubblica è obbligatoria e la psicoterapia rientra in parte nella copertura, ma i percorsi pubblici hanno attese lunghe e l'offerta si concentra a Praga e Brno. Un canale che vale la pena conoscere è quello della <em>Všeobecná zdravotní pojišťovna</em>, la cassa assicurativa più grande del paese: con il proprio programma per la salute mentale mette a disposizione un contributo per il supporto psicosociale presso un terapeuta inserito nell'elenco, per un massimo di dieci sedute e con un tetto complessivo di cinquemila corone (dusevnizdravi.vzp.cz).</p><p>Il contributo non richiede l'impegnativa del medico: si sceglie il terapeuta dall'elenco, si comunica il numero di assicurato al primo incontro e poi si presenta la richiesta, anche online nell'area personale. Non è un rimborso totale della terapia, ma abbatte una parte sensibile della spesa per chi rientra nel programma.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'romania',
    zoneNota: "<h2>Copertura e contratto: come funziona in Romania</h2><p>In Romania la psicologia e la psicoterapia non sono una prestazione a sé: rientrano tra i servizi di salute connessi all'atto medico, erogati da psicologi con specializzazione in psicologia clinica, consulenza psicologica e psicoterapia. Paga il fondo di assicurazione sanitaria, attraverso la <em>Casa Națională de Asigurări de Sănătate</em> e le case territoriali, ma solo a due condizioni: che il fornitore abbia un contratto con la casa di assicurazione e che la specialità rientri tra quelle previste.</p><p>L'accesso passa dall'impegnativa del medico di famiglia o dello specialista: i fornitori di assistenza ambulatoriale di specialità erogano le prestazioni solo sulla base di quel documento. L'attesa dipende dal fornitore convenzionato che ha posti disponibili. Il quadro contrattuale è pubblicato sul sito della CNAS (cnas.ro).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'singapore',
    zoneNota: "<h2>MediSave, MediShield e i team di comunità</h2><p>A Singapore il sistema sanitario si appoggia a risparmi individuali obbligatori. MediSave rimborsa le cure ambulatoriali solo per le condizioni croniche incluse nel programma di gestione delle malattie croniche, tra cui depressione, disturbo bipolare, demenza e ansia, e il medico di famiglia deve aderire al programma dedicato alla salute mentale per poter presentare la richiesta. Le condizioni che restano fuori non sono rimborsabili con MediSave, ma possono ottenere sussidi nei policlinici e negli ambulatori specialistici.</p><p>MediShield Life copre soprattutto il ricovero psichiatrico, mentre le assicurazioni integrative aggiungono copertura sopra quel livello. In parallelo, i team di salute mentale di comunità offrono consulenza e terapia senza costi, perché interamente finanziati dal governo. La fonte è il Ministry of Health (moh.gov.sg).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'slovenia',
    zoneNota: "<h2>Impegnativa, urgenza e attese: la Slovenia</h2><p>In Slovenia l'assicurazione sanitaria obbligatoria fa capo allo <em>ZZZS</em>, l'istituto per l'assicurazione sanitaria. L'accesso alle prestazioni specialistiche ambulatoriali passa da un'impegnativa del medico personale o del medico inviante, con un'eccezione che riguarda da vicino la salute mentale: per la visita e la cura dallo psichiatra l'impegnativa non serve (zavarovanec.zzzs.si).</p><p>Il grado di urgenza lo stabilisce il medico che emette l'impegnativa, e da lì dipende l'attesa massima prevista: si va da ventiquattro ore per i casi urgenti fino a sei mesi per quelli ordinari. La psicologia clinica rientra tra le attività di livello primario contrattualizzate con l'istituto, e gran parte della popolazione integra con un'assicurazione volontaria che copre la differenza. L'offerta privata si concentra a Lubiana e Maribor.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'sudafrica',
    zoneNota: "<h2>Medical aid e settore pubblico: due mondi separati</h2><p>In Sudafrica le sedute rientrano tra i <em>Prescribed Minimum Benefits</em>, le prestazioni che ogni medical scheme è obbligato per legge a coprire: il pagamento è a carico dello scheme del socio, indipendentemente dall'opzione scelta e anche quando i benefici annuali sono esauriti. L'ente che vigila su tutto questo è il <em>Council for Medical Schemes</em>, l'autorità statutaria che regola l'assicurazione sanitaria privata (medicalschemes.co.za).</p><p>Alla copertura si accede attraverso il proprio medical scheme e, per alcune prestazioni, passando da un fornitore designato, con l'eventuale quota a carico del paziente; se il rimborso viene negato, il reclamo si presenta prima allo scheme e poi all'unità di adjudication del Council. Chi non ha un medical aid passa invece dal sistema pubblico, dove l'accesso alla psicoterapia è molto più limitato.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'svezia',
    zoneNota: "<h2>Ticket, attese e privato: la Svezia</h2><p>In Svezia la psicoterapia rientra nella sanità pubblica regionale e si paga con un ticket, ma l'accesso dipende dalle liste della tua regione e cambiano molto da una all'altra: per alcuni servizi basta contattare il centro di prima linea psichiatrica o la vårdcentral, per altri serve un invio. La guida ufficiale della sanità svedese è 1177 Vårdguiden (1177.se).</p><p>Una cosa che molti non sanno: per l'assistenza ambulatoriale esiste un tetto di spesa in dodici mesi, e superata quella soglia si ottiene un <em>frikort</em> e non si paga più per il resto del periodo. Nella sanità interamente privata, senza accordo con una regione, invece si paga l'intero costo. Molti italiani in Svezia partono dal centro di salute e finiscono nel privato.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'thailandia',
    zoneNota: "<h2>Chi paga le sedute in Thailandia</h2><p>In Thailandia il sistema di copertura sanitaria universale, gestito dall'<em>Ufficio nazionale per la sicurezza sanitaria</em>, comprende i servizi di salute mentale in quattro aree: promozione e prevenzione, con screening e valutazione; cure mediche ambulatoriali e per ricoverati; assistenza continuativa nella comunità; riabilitazione per ridurre le ricadute (nhso.go.th).</p><p>Per i cittadini l'accesso non è complicato: si conferma la propria identità con la carta d'identità, si telefona alla linea di salute mentale, oppure ci si presenta all'unità sanitaria di riferimento; se quell'unità non ha capacità sufficiente, la persona viene inviata a un centro specialistico. Per chi arriva dall'estero il quadro cambia: gli stranieri si appoggiano di norma a un'assicurazione internazionale o privata, oppure pagano di tasca, e la psicoterapia è offerta soprattutto in cliniche private e ospedali internazionali tra Bangkok, Phuket e Chiang Mai.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'ungheria',
    zoneNota: "<h2>Copertura pubblica e privato: l'Ungheria</h2><p>In Ungheria l'assicurazione sanitaria obbligatoria ha un'amministrazione dedicata, la <em>NEAK</em>. Nella lista della specialistica ambulatoriale finanziabile c'è una voce precisa per la psicoterapia: la seduta di base breve, condotta da uno psichiatra specialista o da uno psicologo clinico specialista, per almeno trenta minuti. Il costo non è a carico del paziente: è la NEAK a rimborsare successivamente il fornitore convenzionato.</p><p>L'accesso alla specialistica ambulatoriale è gratuito quando si passa da un'impegnativa, oppure quando la specialità è raggiungibile senza, e tra queste c'è la psichiatria. L'attesa resta il punto critico, e per questo una parte consistente delle sedute avviene nel privato, con un'offerta concentrata a Budapest. La fonte è il sito della NEAK (neak.gov.hu).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'uruguay',
    zoneNota: "<h2>Sistema misto: chi paga le sedute in Uruguay</h2><p>In Uruguay la salute mentale ha un posto preciso nel catalogo delle prestazioni del sistema sanitario integrato. Un decreto del 2011 ha inserito il Piano di prestazioni in salute mentale tra le prestazioni garantite e ha reso obbligatoria l'assistenza psicologica in tutti gli erogatori, pubblici e privati, includendo gli approcci psicoterapeutici e psicosociali; un decreto successivo ha esteso la copertura della psicoterapia a una fascia d'età più ampia (gub.uy).</p><p>La prestazione viene erogata direttamente dall'erogatore di riferimento, non sotto forma di rimborso: si accede chiedendo un primo colloquio con il comitato di accoglienza dell'istituzione, di propria iniziativa o su invio dell'équipe sanitaria. L'offerta si concentra a Montevideo, e chi vive nell'interno ha spesso meno scelta e deve spostarsi.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'venezuela',
    zoneNota: "<h2>Chi paga le sedute in Venezuela</h2><p>In Venezuela il riferimento pubblico è il <em>Ministerio del Poder Popular para la Salud</em>, che attraverso il proprio Programma di salute mentale organizza l'assistenza. La difficoltà del sistema è nota e riguarda anche quest'area: gli interventi pubblici documentati sono operazioni territoriali, come il dispiegamento nelle aree di salute integrale comunitaria che ha garantito trattamenti specialistici senza costo, con giornate di valutazione psichiatrica, consulti di psicologia clinica e laboratori di orientamento familiare (mpps.gob.ve).</p><p>Nella pratica, chi può si rivolge al privato: le sedute si pagano di tasca, spesso con tariffe agganciate al dollaro. Gli studi si concentrano a Caracas e nelle città maggiori, mentre fuori da lì l'offerta è molto ridotta. È il contesto in cui una terapia a distanza cambia più radicalmente le opzioni disponibili.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>"
  },
  {
    slug: 'belgio',
    zoneNota: "<h2>Bruxelles non è il Belgio</h2><p>La comunità italiana a Bruxelles vive concentrata tra il Quartiere Europeo, Ixelles ed Etterbeek, dove lavora chi è arrivato per la Commissione, il Parlamento o la NATO. Il risultato è che molti italiani conoscono Bruxelles benissimo e il Belgio quasi per niente. Una parte lavora in Lussemburgo e dorme in Belgio, o il contrario: il treno Bruxelles-Lussemburgo è una routine che si regge per anni e consuma più di quanto si ammetta.</p><h2>Il rimborso delle sedute</h2><p>Sul rimborso è cambiato molto negli ultimi anni. Dal 2021 l'INAMI, l'istituto nazionale che gestisce l'assicurazione malattia, rimborsa le cure psicologiche di prima linea erogate dentro una rete di salute mentale convenzionata, con pagamento diretto al professionista e senza anticipare l'intera cifra (inami.fgov.be). Non è però un percorso libero: passa dalla rete convenzionata e dalla propria mutuelle, e conviene chiedere prima quali sedute copre.</p><p>Le sedute si svolgono in italiano, in videochiamata, e il Belgio è nello stesso fuso orario dell'Italia.</p>",
  },
  {
    slug: 'lussemburgo',
    zoneNota: "<h2>Kirchberg e i fondi: una città che si rinnova</h2><p>Metà della popolazione del Lussemburgo è nata fuori dal paese. Sulla collina di Kirchberg hanno sede la Corte di Giustizia dell'Unione Europea, la Banca Europea per gli Investimenti e la Corte dei Conti; in città lavora la macchina dei fondi e della finanza. Sono ambienti piccoli e intrecciati, e molti scoprono che circondarsi di persone nella propria situazione non basta a legare davvero: i contratti durano due o tre anni e le partenze sono continue.</p><h2>Il rimborso delle sedute</h2><p>Qui la regola è scritta e ha un nome: dal febbraio 2023 la <em>Caisse nationale de santé</em> rimborsa le sedute di psicoterapia presso un professionista riconosciuto, purché prescritte da un medico. Esistono tre tipi di atto, dalla seduta di iniziazione al sostegno prolungato, e l'assicurato anticipa la spesa per poi chiedere il rimborso alla propria cassa: il 70 per cento per gli adulti, il cento per cento per i minori (cns.public.lu).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'qatar',
    zoneNota: "<h2>Dove si trova la terapia, e chi la offre</h2><p>In Qatar il riferimento pubblico è il <em>Ministry of Public Health</em>, che attraverso il Programma nazionale per la salute mentale organizza l'offerta del paese. Le terapie psicologiche di cure primarie, note come Support Clinics, sono attive in alcuni centri di salute, tra cui Leabaib, Rawdat Al Khail, Al Thumama e Al Wajbah, e vi si accede tramite invio del proprio medico (sehanafsia.moph.gov.qa).</p><p>Sul piano assicurativo il quadro è obbligatorio ma frammentato: la legge sui servizi sanitari impone ai datori di lavoro e agli sponsor di assicurare i residenti stranieri, e per i visitatori esiste una polizza dedicata registrata presso il Ministero. Quello che cambia da contratto a contratto è cosa la polizza copre davvero, salute mentale compresa: conviene leggerlo prima di iniziare.</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
  {
    slug: 'austria',
    zoneNota: "<h2>ÖGK: chi copre le sedute in Austria</h2><p>In Austria il riferimento per l'assicurazione malattia è l'<em>Österreichische Gesundheitskasse</em>, la cassa sanitaria che fa capo alla previdenza sociale austriaca. Le prestazioni psicoterapeutiche si possono in linea di principio usare direttamente, senza bisogno di un invio medico: è una differenza importante rispetto a quasi tutti i paesi vicini.</p><p>Per ottenere però una copertura piena o un contributo serve di norma un disturbo psichico riconosciuto come rilevante dal punto di vista clinico e una conferma medica; in mancanza di questi presupposti la prestazione resta privata. Nel settore ambulatoriale il sistema funziona in due modi: o copertura totale presso strutture convenzionate, o rimborso parziale delle spese. La consulenza pura o i percorsi di crescita personale non sono coperti. Il quadro è descritto sul portale sanitario ufficiale (gesundheit.gv.at).</p><p>Le sedute si svolgono in italiano, in videochiamata.</p>",
  },
];
