// Paesi con comunità italiana significativa o grande presenza di expat italiani.
// Ogni voce alimenta una landing unica per paese e una per capitale.
// Struttura: { slug, nome, bandiera, capitale: { slug, nome, nota }, regione, fuso, comunita }
export const paesi = [
  { slug: 'stati-uniti', nome: 'Stati Uniti', bandiera: '🇺🇸', capitale: { slug: 'washington', nome: 'Washington', nota: 'capitale federale e città dove lavorano molti professionisti italiani' }, regione: 'Nord America', fuso: '6-9 ore in meno rispetto all\'Italia', comunita: 'Gli Stati Uniti ospitano una delle comunità italiane più grandi al mondo, da New York alla California', citta: ['New York', 'New Jersey', 'Miami', 'Chicago', 'Los Angeles', 'San Francisco', 'Boston', 'Houston'] },
  { slug: 'canada', nome: 'Canada', bandiera: '🇨🇦', capitale: { slug: 'ottawa', nome: 'Ottawa', nota: 'capitale amministrativa con una comunità italiana attiva' }, regione: 'Nord America', fuso: 'da 6 a 9 ore in meno rispetto all\'Italia', comunita: 'La comunità italiana in Canada è storica e organizzata, con forti presenze a Montréal e Toronto', citta: ['Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Ottawa', 'Hamilton', 'Winnipeg', 'Edmonton'] },
  { slug: 'regno-unito', nome: 'Regno Unito', bandiera: '🇬🇧', capitale: { slug: 'londra', nome: 'Londra', nota: 'prima destinazione europea dei giovani italiani' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'Il Regno Unito ospita una delle comunità italiane più numerose e giovani d\'Europa', citta: ['Londra', 'Manchester', 'Birmingham', 'Glasgow', 'Edimburgo', 'Leeds', 'Leicester', 'Milton Keynes'] },
  { slug: 'francia', nome: 'Francia', bandiera: '🇫🇷', capitale: { slug: 'parigi', nome: 'Parigi', nota: 'capitale con una comunità italiana storica e vivace' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'La comunità italiana in Francia è storica e numerosa, presente in tutto il territorio', citta: ['Parigi', 'Lione', 'Nizza', 'Marsiglia', 'Tolosa', 'Bordeaux', 'Lille', 'Grenoble'] },
  { slug: 'germania', nome: 'Germania', bandiera: '🇩🇪', capitale: { slug: 'berlino', nome: 'Berlino', nota: 'capitale creativa con molti italiani giovani e professionisti' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'La Germania ospita una delle comunità italiane più numerose d\'Europa', citta: ['Berlino', 'Monaco', 'Francoforte', 'Stoccarda', 'Colonia', 'Amburgo', 'Düsseldorf', 'Norimberga'] },
  { slug: 'svizzera', nome: 'Svizzera', bandiera: '🇨🇭', capitale: { slug: 'berna', nome: 'Berna', nota: 'capitale federale, hub di aziende e istituzioni' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'La Svizzera conta una delle comunità italiane più grandi d\'Europa, tra frontalieri e residenti', citta: ['Zurigo', 'Ginevra', 'Lugano', 'Basilea', 'Berna', 'Losanna', 'San Gallo', 'Soletta', 'Glarona', 'Grenchen', 'Herisau', 'Küssnacht', 'Muttenz', 'Arosa', 'Emmen'],
    // Località con una PAGINA PROPRIA, oltre alla capitale. Stessa forma di `capitale`
    // (slug + nome) più i campi di contenuto differenziato: `desc` (meta description),
    // `intro` (paragrafo sotto il titolo), `local` (scheda con i dettagli del posto),
    // `faqLocal` (domande specifiche). È la stessa regola delle città italiane
    // (src/content/citta.js): una pagina locale è indicizzabile SOLO se ha un testo suo.
    // Una pagina templata con il nome cambiato è una pagina porta, e Google la tratta
    // come tale.
    //
    // Perché queste quattro: sono le località per cui Search Console registra già query
    // reali ("psicologo italiano online <luogo>") e per cui non esisteva alcuna pagina —
    // la pagina Svizzera veniva servita come ripiego, a posizione media 34,4. La domanda
    // è misurata, non stimata.
    //
    // Dati citati nei testi (generali, verificati): seduta privata in Svizzera 150-200
    // CHF; riferimento LAMal 155 CHF/ora; dal 1/7/2022 la psicoterapia è a carico
    // dell'assicurazione di base con prescrizione medica, max 15 sedute per ricetta, più
    // franchigia e 10% di partecipazione. Il percorso del sito resta privato e senza
    // prescrizione: non promettere rimborsi.
    cittaPagine: [
      {
        slug: 'lugano',
        nome: 'Lugano',
        nota: 'il cuore della Svizzera italiana, a pochi minuti dal confine',
        intro: "A Lugano la terapia in italiano non è una comodità: è la lingua in cui sei abituato a pensare. In Ticino gli studi privati lavorano già in italiano, ma con tariffe alte e tempi lunghi. Online inizi quando vuoi, a CHF 130 e senza prescrizione.",
        local: `<h3>Terapia online a Lugano: in italiano, senza prescrizione e senza lista d'attesa</h3><p>In Ticino il problema non è trovare un terapeuta che parli italiano — è il <strong>prezzo</strong> e l'<strong>attesa</strong>. Uno studio privato in Svizzera costa mediamente <strong>150-200 CHF</strong> a seduta (il riferimento LAMal è di 155 CHF l'ora) e per il rimborso serve la prescrizione del medico: al massimo <strong>15 sedute per ricetta</strong>, più franchigia e il 10% di partecipazione a tuo carico.</p><p>Con Adatto x Te la seduta individuale da 50 minuti costa <strong>CHF 130</strong> (145 CHF quella di coppia), si paga in euro all'equivalente fisso e la prima seduta conoscitiva è gratuita. Nessuna prescrizione, nessuna diagnosi nel dossier assicurativo, nessuna lista d'attesa: scegli il terapeuta e prenoti.</p><p>Funziona se vivi a Lugano, a Paradiso o in uno dei comuni del Luganese, se fai il frontaliere o se ti sposti spesso fra Ticino e Italia: il percorso non si interrompe quando cambi casa, ufficio o confine.</p>`,
        faqLocal: [
          ["Quanto costa uno psicologo a Lugano?", "In Ticino uno studio privato costa mediamente 150-200 CHF a seduta. Con Adatto x Te la seduta individuale da 50 minuti costa CHF 130, pagabili in euro all'equivalente fisso, e la prima è gratuita."],
          ["Serve la prescrizione del medico per iniziare?", "No, se scegli il percorso diretto: inizi senza prescrizione e senza che nulla finisca nel dossier assicurativo. La prescrizione serve solo se vuoi il rimborso LAMal, e in quel caso il trattamento va svolto da terapeuti riconosciuti in Svizzera (PsiReg)."],
          ["Sono frontaliere: posso seguire le sedute dall'Italia?", "Sì. La videochiamata funziona da qualsiasi luogo e il fuso è lo stesso dell'Italia: puoi fare la seduta da casa in Italia, dall'ufficio a Lugano o in pausa pranzo."]
        ],
        desc: "Psicologo online per italiani a Lugano: sedute video in italiano a CHF 130, prima gratuita, senza prescrizione né lista d'attesa."
      },
      {
        slug: 'zurigo',
        nome: 'Zurigo',
        nota: 'la città più grande della Svizzera',
        intro: "A Zurigo lavori in tedesco o in inglese tutto il giorno. Ma quando si parla di te, la lingua che ti viene naturale è un'altra. Le sedute si svolgono in italiano, con terapeuti italiani.",
        local: `<h3>Terapia in italiano a Zurigo: parlare di sé nella propria lingua</h3><p>Zurigo è la città più grande della Svizzera e una delle mete europee con la maggiore presenza di professionisti italiani. Molti arrivano per lavoro e si trovano a vivere, negoziare, discutere e perfino scherzare in una lingua che non è la loro. In terapia questo pesa più che altrove: raccontare un disagio in tedesco o in inglese è uno sforzo che spesso fa rimandare la richiesta d'aiuto.</p><p>Uno studio privato in Svizzera costa mediamente <strong>150-200 CHF</strong> a seduta, e i terapeuti che lavorano in italiano a Zurigo sono pochi. Online hai un elenco di psicologi e psicoterapeuti italiani a <strong>CHF 130</strong> la seduta da 50 minuti, con la prima conversazione gratuita.</p><p>Se lavori a Zurigo, a Winterthur o lungo la Limmat, oppure sei in smart working e ti sposti, prenoti quando hai un'ora libera: sera, pausa pranzo o weekend.</p>`,
        faqLocal: [
          ["Posso fare terapia in italiano a Zurigo?", "Sì: tutte le sedute si svolgono in italiano con psicologi e psicoterapeuti italiani. Non devi tradurre quello che provi e non perdi le sfumature proprio dove contano."],
          ["Quanto costa rispetto a uno studio a Zurigo?", "In Svizzera una seduta privata costa mediamente 150-200 CHF. Online la seduta individuale da 50 minuti costa CHF 130, con la prima conversazione gratuita."],
          ["Lavoro tutto il giorno: quali orari ci sono?", "Prenoti tu lo slot, anche la sera o nel weekend, con lo stesso fuso dell'Italia. E se ti trasferisci in un'altra città il percorso continua senza interruzioni."]
        ],
        desc: "Psicologo online per italiani a Zurigo: sedute in italiano a CHF 130, prima gratuita. Parla di te nella tua lingua, senza lista d'attesa."
      },
      {
        slug: 'ginevra',
        nome: 'Ginevra',
        nota: 'città internazionale, sede di organizzazioni e grandi aziende',
        intro: "A Ginevra si lavora in francese e in inglese, fra organizzazioni internazionali, missioni e contratti a termine. Le sedute online sono in italiano, con terapeuti italiani.",
        local: `<h3>Terapia in italiano a Ginevra: per chi vive fra contratti e trasferimenti</h3><p>Ginevra è una città di passaggio per mestiere: organizzazioni internazionali, missioni, contratti a durata determinata, trasferimenti ogni pochi anni. È un contesto stimolante e faticoso insieme — e la lingua in cui ti racconti resta l'italiano.</p><p>Uno studio privato in Svizzera costa mediamente <strong>150-200 CHF</strong> a seduta, e per il rimborso LAMal serve la prescrizione del medico (al massimo 15 sedute per ricetta, più franchigia e 10% a tuo carico). Con il percorso diretto paghi <strong>CHF 130</strong> a seduta individuale, in euro all'equivalente fisso, senza prescrizione e senza diagnosi nel dossier assicurativo.</p><p>Se vivi a Ginevra, a Carouge o sulla rive droite, o se il contratto ti porterà altrove fra sei mesi, il percorso online ti segue: stesso terapeuta, stessa lingua, stesso orario.</p>`,
        faqLocal: [
          ["Vivo a Ginevra per lavoro: posso iniziare subito?", "Sì: non serve alcuna prescrizione e non ci sono liste d'attesa. Scegli il terapeuta e prenoti la prima seduta conoscitiva, che è gratuita."],
          ["E se il mio contratto mi porta in un'altra città?", "Il percorso è online: non cambia nulla. Puoi continuare con lo stesso terapeuta anche se ti trasferisci in un altro paese, con lo stesso fuso dell'Italia."],
          ["Il rimborso LAMal è possibile?", "Solo con prescrizione medica e con terapeuti riconosciuti in Svizzera (PsiReg). Il percorso diretto con noi resta privato e riservato: paghi la seduta e niente finisce nel dossier assicurativo."]
        ],
        desc: "Psicologo online per italiani a Ginevra: sedute in italiano a CHF 130, prima gratuita. Nessuna prescrizione, nessuna lista d'attesa."
      },
      {
        slug: 'basilea',
        nome: 'Basilea',
        nota: 'sul Reno, al confine con Germania e Francia',
        intro: "A Basilea vivi a pochi minuti da due paesi e lavori in un ambiente internazionale. Le sedute online si svolgono in italiano, senza spostamenti e senza coincidenze da prendere.",
        local: `<h3>Terapia in italiano a Basilea: per chi vive fra tre paesi</h3><p>A Basilea la giornata attraversa tre paesi: casa in Svizzera, ufficio magari a Weil am Rhein o a Saint-Louis, tempo libero dove capita. È una vita comoda e complicata insieme, e incastrare uno studio di psicoterapia fra dogana, tram e turni non è banale.</p><p>Uno studio privato in Svizzera costa mediamente <strong>150-200 CHF</strong> a seduta, e per il rimborso tramite LAMal serve una prescrizione medica. Online elimini il problema logistico: <strong>CHF 130</strong> la seduta individuale da 50 minuti, prima seduta conoscitiva gratuita, pagamento in euro all'equivalente fisso.</p><p>Funziona anche per chi lavora su turni o in laboratorio con orari che cambiano ogni settimana: sposti la seduta quando serve, senza perdere l'appuntamento.</p>`,
        faqLocal: [
          ["Basilea non è comoda da raggiungere: come funziona?", "È il motivo per cui molti scelgono l'online: nessuno spostamento, nessuna attesa, 50 minuti da casa o dall'ufficio. Scegli tu l'orario, anche la sera."],
          ["Quanto costa rispetto a uno studio a Basilea?", "In Svizzera una seduta privata costa mediamente 150-200 CHF. Con Adatto x Te la seduta individuale costa CHF 130 e la prima è gratuita."],
          ["Lavoro su turni: posso spostare le sedute?", "Sì: prenoti lo slot che ti serve ogni volta. Molti pazienti alternano settimane con orari diversi senza problemi."]
        ],
        desc: "Psicologo online per italiani a Basilea: sedute in italiano a CHF 130, prima gratuita. Nessuna prescrizione, nessuno spostamento."
      }
    ] },
  { slug: 'belgio', nome: 'Belgio', bandiera: '🇧🇪', capitale: { slug: 'bruxelles', nome: 'Bruxelles', nota: 'capitale europea, sede delle istituzioni UE con molti italiani' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'Il Belgio ha una comunità italiana storica, rafforzata dalla presenza delle istituzioni europee', citta: ['Bruxelles', 'Anversa', 'Liegi', 'Gand', 'Charleroi'] },
  { slug: 'spagna', nome: 'Spagna', bandiera: '🇪🇸', capitale: { slug: 'madrid', nome: 'Madrid', nota: 'capitale con una comunità italiana in forte crescita' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'La comunità italiana in Spagna è in forte crescita, soprattutto tra i giovani', citta: ['Madrid', 'Barcellona', 'Valencia', 'Siviglia', 'Malaga', 'Alicante', 'Palma di Maiorca', 'Bilbao'] },
  { slug: 'paesi-bassi', nome: 'Paesi Bassi', bandiera: '🇳🇱', capitale: { slug: 'amsterdam', nome: 'Amsterdam', nota: 'capitale dinamica con molti italiani nel tech e nel design' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'La comunità italiana nei Paesi Bassi è giovane e in crescita, legata a lavoro e studio', citta: ['Amsterdam', 'Rotterdam', 'L\'Aia', 'Utrecht', 'Eindhoven'] },
  { slug: 'irlanda', nome: 'Irlanda', bandiera: '🇮🇪', capitale: { slug: 'dublino', nome: 'Dublino', nota: 'hub tecnologico europeo con una grande presenza italiana' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'L\'Irlanda ha una comunità italiana giovane, legata all\'hub tech di Dublino', citta: ['Dublino', 'Cork', 'Galway', 'Limerick'] },
  { slug: 'austria', nome: 'Austria', bandiera: '🇦🇹', capitale: { slug: 'vienna', nome: 'Vienna', nota: 'capitale con stretti legami storici con l\'Italia' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'L\'Austria ha stretti legami storici e culturali con l\'Italia', citta: ['Vienna', 'Innsbruck', 'Graz', 'Salisburgo', 'Linz'] },
  { slug: 'lussemburgo', nome: 'Lussemburgo', bandiera: '🇱🇺', capitale: { slug: 'lussemburgo', nome: 'Lussemburgo', nota: 'la capitale con la più alta concentrazione di italiani pro capite' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'Il Lussemburgo ha un\'altissima concentrazione di italiani, tra finanza e istituzioni europee', citta: ['Lussemburgo', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Pétange'] },
  { slug: 'portogallo', nome: 'Portogallo', bandiera: '🇵🇹', capitale: { slug: 'lisbona', nome: 'Lisbona', nota: 'capitale che attrae sempre più italiani e digital nomad' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La comunità italiana in Portogallo è in crescita, anche tra i nomadi digitali', citta: ['Lisbona', 'Porto', 'Faro', 'Cascais', 'Braga', 'Coimbra'] },
  { slug: 'australia', nome: 'Australia', bandiera: '🇦🇺', capitale: { slug: 'canberra', nome: 'Canberra', nota: 'capitale amministrativa con comunità italiana presente' }, regione: 'Oceania', fuso: 'da +8 a +10 ore rispetto all\'Italia', comunita: 'La comunità italiana in Australia è storica e organizzata, con forti presenze a Melbourne e Sydney', citta: ['Melbourne', 'Sydney', 'Adelaide', 'Perth', 'Brisbane', 'Gold Coast', 'Canberra', 'Newcastle'] },
  { slug: 'argentina', nome: 'Argentina', bandiera: '🇦🇷', capitale: { slug: 'buenos-aires', nome: 'Buenos Aires', nota: 'capitale con una delle più grandi discendenze italiane' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'L\'Argentina ha una fortissima discendenza italiana e legami culturali profondi', citta: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Mar del Plata', 'Santa Fe', 'Tucumán'] },
  { slug: 'brasile', nome: 'Brasile', bandiera: '🇧🇷', capitale: { slug: 'brasilia', nome: 'Brasilia', nota: 'capitale moderna con comunità italiana presente' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'Il Brasile ha la più grande discendenza italiana fuori dall\'Italia', citta: ['San Paolo', 'Rio de Janeiro', 'Curitiba', 'Porto Alegre', 'Belo Horizonte', 'Florianópolis', 'Campinas', 'Brasilia'] },
  { slug: 'uruguay', nome: 'Uruguay', bandiera: '🇺🇾', capitale: { slug: 'montevideo', nome: 'Montevideo', nota: 'capitale con una fortissima componente di origine italiana' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'L\'Uruguay ha una delle discendenze italiane più alte al mondo', citta: ['Montevideo', 'Salto', 'Paysandú', 'Punta del Este', 'Colonia del Sacramento', 'Rivera'] },
  { slug: 'venezuela', nome: 'Venezuela', bandiera: '🇻🇪', capitale: { slug: 'caracas', nome: 'Caracas', nota: 'capitale con una comunità italiana storica' }, regione: 'Sud America', fuso: 'da -5 a -6 ore rispetto all\'Italia', comunita: 'Il Venezuela ha una comunità italiana storica e radicata', citta: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Mérida'] },
  { slug: 'cile', nome: 'Cile', bandiera: '🇨🇱', capitale: { slug: 'santiago', nome: 'Santiago', nota: 'capitale con una comunità italiana consolidata' }, regione: 'Sud America', fuso: 'da -4 a -5 ore rispetto all\'Italia', comunita: 'Il Cile ha una comunità italiana consolidata, con legami culturali forti', citta: ['Santiago', 'Valparaíso', 'Viña del Mar', 'Concepción', 'Antofagasta', 'La Serena'] },
  { slug: 'messico', nome: 'Messico', bandiera: '🇲🇽', capitale: { slug: 'citta-del-messico', nome: 'Città del Messico', nota: 'capitale con una comunità italiana in crescita' }, regione: 'Nord America', fuso: 'da -7 a -8 ore rispetto all\'Italia', comunita: 'La comunità italiana in Messico è in crescita, tra aziende e istituzioni', citta: ['Città del Messico', 'Guadalajara', 'Monterrey', 'Puebla', 'Querétaro', 'Cancún'] },
  { slug: 'emirati-arabi', nome: 'Emirati Arabi', bandiera: '🇦🇪', capitale: { slug: 'abu-dhabi', nome: 'Abu Dhabi', nota: 'capitale con molti professionisti italiani in azienda' }, regione: 'Medio Oriente', fuso: '+2 ore rispetto all\'Italia', comunita: 'Gli Emirati Arabi contano molti professionisti italiani in finanza, energia e costruzioni', citta: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman'] },
  { slug: 'singapore', nome: 'Singapore', bandiera: '🇸🇬', capitale: { slug: 'singapore', nome: 'Singapore', nota: 'città-stato, hub finanziario asiatico con italiani in carriera' }, regione: 'Asia', fuso: '+6 ore rispetto all\'Italia', comunita: 'Singapore ospita una comunità di professionisti italiani in finanza e tech', citta: ['Singapore'] },
  { slug: 'cina', nome: 'Cina', bandiera: '🇨🇳', capitale: { slug: 'pechino', nome: 'Pechino', nota: 'capitale con una presenza italiana tra istituzioni e imprese' }, regione: 'Asia', fuso: '+7 ore rispetto all\'Italia', comunita: 'La Cina ha una presenza italiana tra Pechino e Shanghai, soprattutto per lavoro', citta: ['Shanghai', 'Pechino', 'Hong Kong', 'Canton', 'Shenzhen', 'Suzhou', 'Hangzhou'] },
  { slug: 'giappone', nome: 'Giappone', bandiera: '🇯🇵', capitale: { slug: 'tokyo', nome: 'Tokyo', nota: 'capitale con una piccola ma attiva comunità italiana' }, regione: 'Asia', fuso: '+8 ore rispetto all\'Italia', comunita: 'Il Giappone ha una comunità italiana piccola ma attiva, tra moda, design e aziende', citta: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya'] },
  { slug: 'sudafrica', nome: 'Sudafrica', bandiera: '🇿🇦', capitale: { slug: 'pretoria', nome: 'Pretoria', nota: 'capitale amministrativa con comunità italiana storica' }, regione: 'Africa', fuso: 'da 0 a +1 ora rispetto all\'Italia', comunita: 'Il Sudafrica ha una comunità italiana storica, con presenze a Johannesburg e Città del Capo', citta: ['Johannesburg', 'Città del Capo', 'Durban', 'Pretoria', 'Port Elizabeth'] },
  { slug: 'nuova-zelanda', nome: 'Nuova Zelanda', bandiera: '🇳🇿', capitale: { slug: 'wellington', nome: 'Wellington', nota: 'capitale con una comunità italiana piccola ma attiva' }, regione: 'Oceania', fuso: 'da +10 a +12 ore rispetto all\'Italia', comunita: 'La Nuova Zelanda ha una comunità italiana storica e in crescita, legata a studio e lavoro', citta: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Queenstown'] },
  { slug: 'malta', nome: 'Malta', bandiera: '🇲🇹', capitale: { slug: 'la-valletta', nome: 'La Valletta', nota: 'capitale con moltissimi italiani residenti' }, regione: 'Europa', fuso: 'stesso orario dell\'Italia', comunita: 'Malta conta moltissimi italiani tra studio, lavoro e impresa', citta: ['La Valletta', 'Sliema', 'St Julian\'s', 'Birkirkara', 'Mosta', 'Qormi'] },
  { slug: 'svezia', nome: 'Svezia', bandiera: '🇸🇪', capitale: { slug: 'stoccolma', nome: 'Stoccolma', nota: 'capitale scandinava con una comunità italiana in crescita' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La comunità italiana in Svezia è in crescita, tra lavoro e studio', citta: ['Stoccolma', 'Göteborg', 'Malmö', 'Uppsala', 'Västerås', 'Linköping'] },
  { slug: 'danimarca', nome: 'Danimarca', bandiera: '🇩🇰', capitale: { slug: 'copenaghen', nome: 'Copenaghen', nota: 'capitale con una comunità italiana giovane' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Danimarca ha una comunità italiana giovane, legata a università e aziende', citta: ['Copenaghen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'] },
  { slug: 'norvegia', nome: 'Norvegia', bandiera: '🇳🇴', capitale: { slug: 'oslo', nome: 'Oslo', nota: 'capitale con italiani presenti in vari settori' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Norvegia ha una comunità italiana legata a lavoro, ricerca e settore marittimo', citta: ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Tromsø'] },
  { slug: 'finlandia', nome: 'Finlandia', bandiera: '🇫🇮', capitale: { slug: 'helsinki', nome: 'Helsinki', nota: 'capitale nordica con una piccola comunità italiana' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Finlandia ha una comunità italiana piccola ma attiva tra design e tecnologia', citta: ['Helsinki', 'Espoo', 'Tampere', 'Turku', 'Oulu'] },
  { slug: 'polonia', nome: 'Polonia', bandiera: '🇵🇱', capitale: { slug: 'varsavia', nome: 'Varsavia', nota: 'capitale con professionisti italiani in crescita' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Polonia vede crescere i professionisti italiani, tra aziende e istituzioni', citta: ['Varsavia', 'Cracovia', 'Danzica', 'Breslavia', 'Poznań', 'Łódź', 'Katowice'] },
  { slug: 'romania', nome: 'Romania', bandiera: '🇷🇴', capitale: { slug: 'bucarest', nome: 'Bucarest', nota: 'capitale con una comunità imprenditoriale italiana' }, regione: 'Europa', fuso: '1 ora in più rispetto all\'Italia', comunita: 'La Romania ha una comunità imprenditoriale italiana molto presente', citta: ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Costanza', 'Brașov', 'Sibiu', 'Oradea'] },
  { slug: 'ungheria', nome: 'Ungheria', bandiera: '🇭🇺', capitale: { slug: 'budapest', nome: 'Budapest', nota: 'capitale con una comunità italiana attiva' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'L\'Ungheria ha una comunità italiana attiva tra aziende e università', citta: ['Budapest', 'Seghedino', 'Debrecen', 'Pécs', 'Győr', 'Miskolc'] },
  { slug: 'repubblica-ceca', nome: 'Repubblica Ceca', bandiera: '🇨🇿', capitale: { slug: 'praga', nome: 'Praga', nota: 'capitale che attrae molti italiani per lavoro' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Repubblica Ceca vede crescere gli italiani, tra aziende e studio', citta: ['Praga', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'] },
  { slug: 'grecia', nome: 'Grecia', bandiera: '🇬🇷', capitale: { slug: 'atene', nome: 'Atene', nota: 'capitale con legami storici con l\'Italia' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Grecia ha una comunità italiana storica e una presenza imprenditoriale', citta: ['Atene', 'Salonicco', 'Patrasso', 'Candia', 'Larissa', 'Corfù', 'Volos'] },
  { slug: 'croazia', nome: 'Croazia', bandiera: '🇭🇷', capitale: { slug: 'zagabria', nome: 'Zagabria', nota: 'capitale vicina all\'Italia, con comunità italiana presente' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Croazia è vicina di casa: la presenza italiana è diffusa lungo la costa', citta: ['Zagabria', 'Fiume', 'Spalato', 'Pola', 'Zara', 'Ragusa'] },
  { slug: 'slovenia', nome: 'Slovenia', bandiera: '🇸🇮', capitale: { slug: 'lubiana', nome: 'Lubiana', nota: 'capitale al confine con l\'Italia' }, regione: 'Europa', fuso: '1 ora in meno rispetto all\'Italia', comunita: 'La Slovenia confina direttamente con l\'Italia: molti italiani la scelgono per lavoro e famiglia', citta: ['Lubiana', 'Maribor', 'Capodistria', 'Pirano', 'Nova Gorica', 'Isola', 'Celje'] },
  { slug: 'israele', nome: 'Israele', bandiera: '🇮🇱', capitale: { slug: 'gerusalemme', nome: 'Gerusalemme', nota: 'capitale con una presenza italiana tra istituzioni e aziende' }, regione: 'Medio Oriente', fuso: '1 ora in più rispetto all\'Italia', comunita: 'Israele ha una presenza italiana tra tecnologia e istituzioni', citta: ['Tel Aviv', 'Gerusalemme', 'Haifa', 'Netanya'] },
  { slug: 'qatar', nome: 'Qatar', bandiera: '🇶🇦', capitale: { slug: 'doha', nome: 'Doha', nota: 'capitale con molti professionisti italiani' }, regione: 'Medio Oriente', fuso: '+2 ore rispetto all\'Italia', comunita: 'Il Qatar conta professionisti italiani in energia, costruzioni e ospitalità', citta: ['Doha', 'Lusail', 'Al Rayyan', 'Al Wakrah', 'Al Khor'] },
  { slug: 'corea-del-sud', nome: 'Corea del Sud', bandiera: '🇰🇷', capitale: { slug: 'seul', nome: 'Seul', nota: 'capitale con presenza italiana tra moda e tecnologia' }, regione: 'Asia', fuso: '+8 ore rispetto all\'Italia', comunita: 'La Corea del Sud ha una presenza italiana tra moda, design e tecnologia', citta: ['Seul', 'Busan', 'Incheon', 'Daejeon', 'Daegu'] },
  { slug: 'india', nome: 'India', bandiera: '🇮🇳', capitale: { slug: 'nuova-delhi', nome: 'Nuova Delhi', nota: 'capitale con italiani tra aziende e istituzioni' }, regione: 'Asia', fuso: '+4 ore e 30 minuti rispetto all\'Italia', comunita: 'L\'India conta professionisti italiani tra aziende, commercio e istituzioni', citta: ['Nuova Delhi', 'Mumbai', 'Bangalore', 'Calcutta', 'Chennai', 'Hyderabad', 'Pune'] },
  { slug: 'thailandia', nome: 'Thailandia', bandiera: '🇹🇭', capitale: { slug: 'bangkok', nome: 'Bangkok', nota: 'capitale con italiani residenti e imprenditori' }, regione: 'Asia', fuso: '+6 ore rispetto all\'Italia', comunita: 'La Thailandia ospita italiani residenti, imprenditori e pensionati', citta: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hua Hin', 'Ko Samui'] },
];
